### ISSUE TITLE
`make_afun` formats don't cover all `fun` results with the same name 

### ISSUE THREAD

**Issue by danielinteractive** [Roche/rtables#101]
If the statistics function `fun` returns multiple results with the same name in the list, only the first are correctly processed with formatting through `make_afun`. We would like that all results with the matching name are processed as such.
(Note: We need this functionality to group together results of a common "class" that are not appearing all consecutively, and have been using this with our prototype so far.)

Example:

```r
sfun <- function(x) {
  list(
    a = with_label(mean(x), "mean"),
    a = with_label(mean(x, trim = 0.1), "mean (trim 0.1)"),
    a = with_label(mean(x, trim = 0.2), "mean (trim 0.2)")
  )
}
afun <- make_afun(
  sfun,
  .formats = c(a = "xx.xxxx"),
  .indent_mods = c(a = 1L)
)
result <- basic_table() %>%
  analyze("Sepal.Length", afun = afun) %>%
  build_table(iris)
result
##                      all obs     
## ----------------------------------
##   mean                 5.8433     
## mean (trim 0.1)   5.80833333333333
## mean (trim 0.2)   5.79777777777778
```

So here the indent and numeric format is only applied to the first row, but not to the last 2 rows.

Session info:
```r
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 9 (stretch)

Matrix products: default
BLAS/LAPACK: /usr/lib/libopenblasp-r0.2.19.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C             
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rtables_0.3.2.17.9025 magrittr_1.5         

loaded via a namespace (and not attached):
[1] compiler_3.6.3  htmltools_0.4.0 tools_3.6.3     Rcpp_1.0.4.6    digest_0.6.25   packrat_0.5.0  
[7] rlang_0.4.5     purrr_0.3.4 
```

**Comment by gmbecker** [comment]
This is standard named element behavior selection behavior. It is
*exceedingly* bad practice to have duplicate names in an R object and i'm
not convinced that this is something we should support. We should talk
about this, more but this really is not something you should be doing if I
am understanding what you're describing correctly.

**Comment by danielinteractive** [comment]
Thanks Gabe, I am aware that this is a hack at the level of implementation, i.e. using R names for this. However, in terms of logic, this still makes sense when we consider the name as a class of statistic that is returned in the list. 

Unfortunately, we needed this hack in a couple of tables already so far. This mainly occurs when things look like a split in the layout, but actually are not splits. Then, we need a mechanism to be able to indent something more than something else. For example in the table below, we have real row splits on parameter and visit, but inside we have a "nested analysis" I would describe it, where the "Low" and "High" parts are not splits. In this example we solved this by having 4 different statistics: 1) section_label (which just gives "Low" and "High"), then 2) not_abnormal, 3) abnormal, 4) total. Note that 1-3 have labels computed by the stats function. Then we can say please indent stats 2-4 by 1 more than the section_label, and we have our layout below.

````
                                         A: Drug X        B: Placebo     C: Combination
                                          (N=134)          (N=134)          (N=132)    
---------------------------------------------------------------------------------------
Alanine Aminotransferase Measurement                                                   
  WEEK 1 DAY 8                                                                         
    Low                                                                                
     Not low baseline status           10/124 (8.1%)     8/122 (6.6%)     6/117 (5.1%) 
     Low baseline status                 2/10 (20%)          0/12             0/15     
     Total                              12/134 (9%)       8/134 (6%)      6/132 (4.5%) 
    High                                                                               
     Not high baseline status          10/121 (8.3%)    11/118 (9.3%)    11/118 (9.3%) 
     High baseline status               1/13 (7.7%)      2/16 (12.5%)     1/14 (7.1%)  
     Total                             11/134 (8.2%)    13/134 (9.7%)    12/132 (9.1%) 
  WEEK 2 DAY 15                                                                        
    Low                                                                                
     Not low baseline status           13/124 (10.5%)    8/122 (6.6%)    13/117 (11.1%)
     Low baseline status                 2/10 (20%)          0/12             0/15     
     Total                             15/134 (11.2%)     8/134 (6%)     13/132 (9.8%) 
    High                                                                               
     Not high baseline status           8/121 (6.6%)     13/118 (11%)    15/118 (12.7%)
     High baseline status               1/13 (7.7%)      2/16 (12.5%)     1/14 (7.1%)  
     Total                              9/134 (6.7%)    15/134 (11.2%)   16/132 (12.1%)
  WEEK 3 DAY 22                                                                        
    Low                                                                                
     Not low baseline status           12/124 (9.7%)    13/122 (10.7%)    6/117 (5.1%) 
     Low baseline status                 1/10 (10%)      2/12 (16.7%)      3/15 (20%)  
     Total                             13/134 (9.7%)    15/134 (11.2%)    9/132 (6.8%) 
    High                                                                               
     Not high baseline status          12/121 (9.9%)    16/118 (13.6%)   14/118 (11.9%)
     High baseline status               1/13 (7.7%)      2/16 (12.5%)         0/14     
     Total                             13/134 (9.7%)    18/134 (13.4%)   14/132 (10.6%)
````

It would definitely better to have a real rtables mechanism for such nested analyses. E.g. I could imagine having a function `nested_analyze` or just `nested = TRUE` in `analyze` enabling the use of nested lists from stats functions, where we could return from the stats function things like this above:

```r
list(
  abnormal = list(
    low = with_label(label = "Low", x = list(
      with_label(..., "Not low baseline status"),
      with_label(..., "Low baseline status"),
      with_label(..., "Total")
    )),
    high = with_label(label = "High", x = list(
      with_label(..., "Not high baseline status"),
      with_label(..., "High baseline status"),
      with_label(..., "Total")
    ))
  )
)
```
Then the layout framework in rtables could understand that it should indent things in such a way as to reflect the list hierarchy.

But in absence of such a mechanism, I don't know how else to implement this. If you have an idea please let me know.

**Comment by gmbecker** [comment]
So generally, things that look like splits should be splits. The thing that I see missing here is the ability for the analysis function to know what branch of its parent-split it is in. It is true that that is not currently possible, but I will change that shortly.

Once that is true, that an analysis function can take, say `.parent_splval` (or whatever I call it), you would write your analysis function as follows:

```
sfun <- function(x, .N_col, .parent_splval) {
     list(abnormal = with_label(...,  sprintf("Not %s baseline status", tolower(.parent_splval)),
            normal = with_label(...,  sprintf("%s baseline status", .parent_splval)),
            total = with_label(..., "Total"))
}

afun <- make_afun(sfun, .formats = c(...))
```

Then you have a variable representing whatever is being split into the `Low` and `High` pseudo-splits, which you actually split on and then analyze with the above afun. 

The fact that its a real split would give you the "section labels" and indenting for free, and the same function is appleid for each section, its only the labels that are different and in what I wrote above they are dynamic on where in the tree they are, just like split-representing rows are.

Am I correct in thinking this would solve your use-cases where you feel you need what you described? @danielinteractive

**Comment by danielinteractive** [comment]
Thanks Gabe. I think this could work. 
- Regarding the new feature, may I suggest to then have this symmetric for rows and columns, i.e. have both `.row_split_val` and `.col_split_val` available e.g. to the analysis functions? (We also already have use cases, that make use of `.df_row`, where we also need `.col_split_val`)
- The disadvantage I see here is that the user will need to prepare the dataset in a potentially slightly artificial way in this approach. I will check with my colleague whether it could still work in this example.

**Comment by danielinteractive** [comment]
So after discussing (and we might need to look into it more when the feature is available - which is very useful anyway also for other use cases) - seems like the preprocessing could be a bit artificial, because in this case also "High" rows are needed when doing "Low" calculations. But it should be doable. (It could also slow down execution when we need to blow up the data set like this)
Again this is where I was thinking about - can we have something hierarchical in layout, which is not a data split? (but an analysis logic)

**Comment by gmbecker** [comment]
@danielinteractive if both blocks need the full set of data rows, it seems like those are just straightforwardly 2 different `analyze` calls (which can also have section labels, and will by default if you have more than one in particular position in the table, remember). Would that work?

**Comment by danielinteractive** [comment]
Thanks Gabe, we will try this out and come back to you.

**Comment by danielinteractive** [comment]
So we tested this and indeed this solves our design problem here. Thanks again!
