### ISSUE TITLE
`make_afun` result in package triggers R CMD check note

### ISSUE THREAD

**Issue by danielinteractive** [Roche/rtables#103]
For example, we have a function `c_num_patients` produced by `make_afun` in our package code. Then R CMD check triggers the following note:

````
N  checking R code for possible problems (13.3s)
   c_num_patients: no visible binding for global variable ‘x’
   Undefined global functions or variables:
     x
````

While this can be quickly "fixed" by setting

```r
utils::globalVariables(c("x"))
```

in the package, I wonder whether this could be solved more elegantly on rtables side?

**Comment by gmbecker** [comment]
I have created a df-accepting test afun in the package now so if this reverts rtables will exhibit the note.
