### ISSUE TITLE
add option to remove original levels when using `add_combo_levels`

### ISSUE THREAD

**Issue by danielinteractive** [Roche/rtables#104]
I am currently trying to produce a table that looks like this:

````
                                         ARM A                          ARM B            
                                        (N=185)                        (N=180)           
                             _____________________________  _____________________________
                                                                                         
  MedDRA System Organ Class  Any Grade  Grade 3-4  Grade 5  Any Grade  Grade 3-4  Grade 5
    MedDRA Preferred Term       (%)        (%)       (%)       (%)        (%)       (%)  
  _______________________________________________________________________________________
                                                                                         
  SKIN AND SUBCUTANEOUS TISSUE DISORDERS                                                     
    ALOPECIA                    49          1         0        57          0         0   
    RASH                        16         <1         0        12          0         0   
    PRURITUS                    15          0         0         7          0         0   
                                                                                         
  GENERAL DISORDERS AND ADMINISTRATION SITE CONDITIONS                                       
    FATIGUE                     42          4         0        44          3         0   
    PYREXIA                     12         <1         0        10         <1         0   
    OEDEMA PERIPHERAL           12          0         0         8         <1         0   
    ASTHENIA                    12          2         0        10          0         0   
````

My approach was to have three logical variables representing the three analysis columns, and then use `analyze_colvars`. The problem there is that the row split (e.g. "ALOPECIA") gets its own row, but I would like to have the percentage from `analyze_colvars` in the same row as the row split label. Then I thought of `summarize_row_groups` but that cannot handle the different column variables distinctly, i.e. the summary is the same across the 3 analysis columns.

Is there something missing here in terms of feature? Or am I missing something?

**Comment by gmbecker** [comment]
Hi @danielinteractive, so this will be done in rtables with the `add_combo_levels` split function after a small tweak to that function that lets you tell it to drop the original levels. More generally its a custom function problem, not a colvars problem, but again, add_combo_levels is like 90% of the way there (you can get all those columns, just currently not also have the singular levels. Thats an easy fix though which i will do.

**Comment by danielinteractive** [comment]
Thanks Gabe, can you maybe give an example that is close to the table above? That would help me to understand your idea I guess. Note that my main problem here was to have the "data rows" on the same line as the split level labels on the left column.

**Comment by danielinteractive** [comment]
@gmbecker OK I think I have understood your point. So I use the custom splits together with regular `analyze` on factor and it works out regarding formatting nicely! If you could add the option to remove the original levels that will be great, thanks - then this will make this table ready basically.

**Comment by gmbecker** [comment]
See the new example in `?add_combo_levels` @danielinteractive

**Comment by danielinteractive** [comment]
Great, thanks for the new feature Gabe.
