### ISSUE TITLE
Question on how to account for metadata info in pruning

### ISSUE THREAD

**Issue by danielinteractive** [Roche/rtables#109]
Sometimes splitting on factor levels introduces row combinations in a table which are not realistic or possible based on metadata information. For such cases, we would like to come up with an approach to prune based on table data but also taking into account the metadata.

Example:
```r
df <- data.frame(
  arm = c("a", "b", "c", "a", "b", "c"),
  discont = factor(c("dropout", "none", "none", "adverse", "moving", "none"), 
                   levels = c("none", "dropout", "moving", "notime", "adverse", "death", "ill", "reaction")),
  discont_group = factor(c("other", "none", "none", "safety", "other", "none"))
)

tab <- basic_table() %>%
  split_cols_by("arm") %>%
  split_rows_by("discont_group", split_fun = keep_split_levels(c("safety", "other"))) %>%
  split_rows_by("discont") %>%
  summarize_row_groups() %>%
  build_table(df)
tab
prune_table(tab)
```

Now here the problem is:
- `tab` is too large, i.e. contains many rows which don't have observations and which are not possible at all. For example, there can't be a row under "safety" which is "moving".
- `prune_table(tab)` (which somehow kills everything here, but supposing it works) would be too small, i.e. does not contain rows we would like to show having 0s. For example, we would like to keep the row "death" under "safety" to show that it did not happen here.

So the question is how do we include best the requirement here to have specific levels shown for the 2nd factor given the value of the 1st factor?

**Comment by waddella** [comment]
@gmbecker it would be great if you could make a pruner example for

```
(A  > a, b, c, d)
(B > i, ii, iii)
```

```r
df <- tribble(
~U, ~L,
 A,  a,
 A, c,
 B, ii
)
```

**Comment by anajens** [comment]
@gmbecker any update on the example for how the pruning should be done?

**Comment by anajens** [comment]
Thanks so much @gmbecker, we will give this a try and see how it works in a few different layouts. 

If it's working well, would it be possible to include this in the devel branch instead of gable_tabletree so that it can be part of the next release planned for May 5th?

**Comment by gmbecker** [comment]
Closing this issue. @anajens @danielinteractive please reopen if the function (which has been added to the package, currently only in gabe_tabletree_work) doesn't work or is insufficient for your needs
