### ISSUE TITLE
Can we change the "all obs" title of the default column?

### ISSUE THREAD

**Issue by danielinteractive** [Roche/rtables#110]
Can we change the "all obs" title of the default column?

**Comment by gmbecker** [comment]
Currently you can use `add_overall_col` like so:

```
> basic_table() %>% add_overall_col("New overall label") %>% analyze("wt", mean) %>% build_table(mtcars)
       New overall label
------------------------
mean        3.21725     
```

In the future this may also be possible via an argument to `basic_table`, but currently it is not.

**Comment by danielinteractive** [comment]
That is perfectly sufficient, thanks @gmbecker
