### ISSUE TITLE
How to get the right percentages in this case?...

### ISSUE THREAD

**Issue by danielinteractive** [Roche/rtables#117]
Hi @gmbecker 
I have a question on a table layout where

- header column counts set with `col_counts` are from overall population
- `summarize_row_groups` gives us the analysis population column counts
- and then we do `split_rows_by` and we want then percentages that refer to the analysis population, not the overall population...

something like this - but with e.g. 57.4% instead of 7.3% for Patients with event in column A.

````
                                       A: Drug X        B: Placebo      C: Combination 
                                        (N=536)           (N=536)           (N=528)    
---------------------------------------------------------------------------------------
Responders                                68                73                62       
  Patients with event (%)              39 (7.3%)         47 (8.8%)        59 (11.2%)   
    Adverse Event                          6                10                18       
    Death                                  5                 8                 7       
    Disease Progression                   16                 7                10       
    Last Date Known To Be Alive            7                11                12       
    Last Tumor Assessment                  5                11                12       
  Patients without event (%)          29 (42.6%)        26 (35.6%)         3 (4.8%)    
````

When playing around with it I did not have an idea how to do this, since we would need to refer to parent split `nrow(df)` right?...

Thanks!

**Comment by waddella** [comment]
@danielinteractive & @anajens can we close this issue or should we put it on our backlog?

**Comment by danielinteractive** [comment]
I think this is quite important to solve. @anajens what do you think?

**Comment by waddella** [comment]
@gmbecker will think about it. We can discuss it next week in more detail.

**Comment by gmbecker** [comment]
See https://github.com/Roche/rtables/issues/240#issuecomment-923410803

**Comment by gmbecker** [comment]
I believe this can be closed as solved (see linked comment above).

**Comment by danielinteractive** [comment]
Thanks @gmbecker , deferring to @anajens since I am a bit out of the loop at this point

**Comment by gmbecker** [comment]
This is covered by the `.spl_context` functionality.
