### ISSUE TITLE
allow a responsive table argument for as_html

### ISSUE THREAD

**Issue by kieranjmartin** [Roche/rtables#12]
In the context of shiny, it would be useful to produce tables of class  "table-responsive", as in bootstrap they then scroll if they break the size limits given for them, rather than expand over other elements. This would be a useful optional argument to as_html().

**Comment by waddella** [comment]
Hi @kieranjmartin,

Please install the latest development version from the `master` branch.

`as_html.rtable` has now the argument `class.table`. For  `"table-responsive"` in bootstrap 3 you need to wrap it into a `div` element as follows:

```r
library(rtables)
tbl1 <- rtabulate(iris$Sepal.Length, col_by = iris$Species)

tbl2 <- htmltools::tags$div(
  class = "table-responsive",
  as_html(tbl, class.table = "table")
)
``` 

Note I have also updated the `Viewer` function to accept objects of class `shiny.tag` so now you can run

```r
Viewer(tbl2)
```

and

```r
Viewer(tbl1, tbl2)
```

As from bootstrap 4 we will be able to use

```r
 as_html(tbl, class.table = "table table-responsive")
```

Thanks for bringing this up! Does my answer/changes solve the issue?

Best,
Adrian

**Comment by waddella** [comment]
@kieranjmartin, I will close this issue. If you think it should be made the standard argument different feel free to reopen the issue.
