### ISSUE TITLE
How to add line break in rtable headers?

### ISSUE THREAD

**Issue by anajens** [Roche/rtables#134]
Is it possible to add line breaks in rtable headers? 

For example, starting with this table...
```
df <- data.frame(
  n = 1,
  median = 10
)

basic_table() %>%
  split_cols_by_multivar(vars = c("n", "median"), varlabels = c("N", "Median (Days)")) %>%
  analyze_colvars(afun = mean) %>%
  build_table(df)

```
... I would like to be able to control the rtable header so it looks like so:
```
            Median
         n  (Days)
-----------------
mean     1     10
```

When I try inserting `\n`, this gives an error:
```
basic_table() %>%
  split_cols_by_multivar(vars = c("n", "median"), varlabels = c("n", "Median \n (Days)")) %>%
  analyze_colvars(afun = mean) %>%
  build_table(df)
```
Session info:
```
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 9 (stretch)

Matrix products: default
BLAS/LAPACK: /usr/lib/libopenblasp-r0.2.19.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C             
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rtables_0.3.2.17.9045 magrittr_1.5         

loaded via a namespace (and not attached):
[1] compiler_3.6.3  htmltools_0.4.0 tools_3.6.3     Rcpp_1.0.4.6    digest_0.6.25   packrat_0.5.0   rlang_0.4.6     purrr_0.3.4    
```

**Comment by danielinteractive** [comment]
Agree that this would be nice to have. Let's discuss in our next dependencies meeting re: priority and complexity. @gmbecker @waddella

**Comment by danielinteractive** [comment]
Also need more time for this

**Comment by waddella** [comment]
I.e the `toString` and `as_html` need to respect `\n` in the factor levels of the `split_cols_by`.

```r
lyt <- basic_table() %>%
  split_cols_by("ARM") %>%
  analyze(...)

tbl <- build_table(lyt, data %>% mutate(ARM = fct_lvl_add_line_break(ARM, 10)))
```

So `rtables` would not do any word wrapping and convenience functions to do so would have to be created elsewhere. Or the line breaking is done manually in the factor levels.

**Comment by anajens** [comment]
Sorry for the late reply @waddella. I think your proposal makes and it's fine to keep tabulation and printing separate.

**Comment by gmbecker** [comment]
I have pushed the corresponding changes to devel in version `0.3.7.0007`. I believe this is full closed in that newlines are supported everywhere (except top_left values), and for both ASCII (ie printing) and html outputs.
