### ISSUE TITLE
character column split variable can easily lead to wrong column counts assignment

### ISSUE THREAD

**Issue by danielinteractive** [Roche/rtables#154]
Hi Gabe,

we found the following issue in the latest rtables:

```r
col_counts <- c(`ARM A` = 103L, `ARM B` = 98L, `ARM C` = 94L)
df_factor <- data.frame(ARM = c("ARM C", "ARM B", "ARM A"), stringsAsFactors = TRUE)
df_character <- data.frame(ARM = c("ARM C", "ARM B", "ARM A"), stringsAsFactors = FALSE)

lyt <- basic_table() %>%
  split_cols_by(var = "ARM") %>%
  add_colcounts()

result_factor <- build_table(
  lyt = lyt,
  df = df_factor,
  col_counts = col_counts
)
result_factor

result_character <- build_table(
  lyt = lyt,
  df = df_character,
  col_counts = col_counts
)
result_character
```

Here `result_character` puts the "ARM C" first (apparently because it first appears in the data set) but still puts the column count for "ARM A" in the first column. 
Most users would expect that 1) the column order is according to a default factor conversion, i.e. having "ARM A" in the first column and 2) using provided names in `col_counts` to match with the columns. Not sure if that would be easy to fix? Thanks, cheers, Daniel

**Comment by gmbecker** [comment]
Hi @danielinteractive,

So tackling this one ended up being larger scope than hoped. So here is what has happened.

1.  the `col_counts` argument to build_table is now deprecated (I may undeprecate it again after discussions tomorrow but if so it isn't going to respect names and using it is very much going to be an anti-pattern, see below)
2. I have added a `alt_counts_df`  argument to build_table that accepts a data.frame (or tibble) and behaves as per your suggestion.  It simply applies the column subset expressions created using `df` (the main data) to `alt_counts_df` and counts the observations in each resulting split. It does not support displaying non-leaf level counts at this time.

The reason for this is dealing with ordering of override counts is seriously non-trivial when there are nested column splits in play. names can't be used to resolve it, at least not at all easily or in a way I think end-users would be happy with. I can't think of any safe way to do it other than by pure position, but I agree that it is probably too easy to have bugs there (especially given how important these tables are going to be). 

cc @waddella please look at this so we can discuss it

**Comment by danielinteractive** [comment]
Thanks @gmbecker . @waddella we are working on required PRs now internally.

**Comment by waddella** [comment]
what about throwing an error if `split_col_*` gets a reference to character variable? This way only factors can be used and then also the order is deterministic.

**Comment by gmbecker** [comment]
col_counts override has been undeprecated but will throw an error if used in conjunction with splitting on variables that contain character data due to the data-dependent order of the resulting columns.
