### ISSUE TITLE
Add labels from row splits to table header

### ISSUE THREAD

**Issue by anajens** [Roche/rtables#164]
It would be very helpful and increase readability if users can choose if labels from row-splits and `analyze` / `summarize_row_groups` should be added as a row labels or added to the header of a table.

Here's an example:

```
library(rtables)

basic_table() %>%
  split_rows_by("SEX", split_fun = drop_split_levels, visible_label = TRUE) %>%
  split_rows_by("STRATA1", split_fun = drop_split_levels, visible_label = TRUE) %>%
  analyze("BMRKR2", show_labels = "visible") %>%
  build_table(ex_adsl)
```

The result looks like this:
```
                     all obs
----------------------------
SEX                         
  F                         
    STRATA1                 
      A                     
        BMRKR2              
          LOW          26   
          MEDIUM       19   
          HIGH         18   
      B                     
        BMRKR2              
          LOW          19   
          MEDIUM       33   
          HIGH         21   
      C                     
        BMRKR2              
          LOW          28   
          MEDIUM       24   
          HIGH         34   
  M                         
    STRATA1                 
      A                     
        BMRKR2              
          LOW          14   
          MEDIUM       20   
          HIGH         21   
      B                     
        BMRKR2              
          LOW          21   
  ...
```
Ideally, the labels be added to the header:
```
SEX
  STRATA1
    BMRKR2      all obs
----------------------------
F                         
 A                     
    LOW              26   
    MEDIUM           19   
    HIGH             18   
 B                     
    LOW              19   
    MEDIUM           33   
    HIGH             21   
 C                     
    LOW              28   
    MEDIUM           24   
    HIGH             34   
M                         
 A                     
    LOW              14   
    MEDIUM           20   
    HIGH             21   
 B                     
    LOW              21 
 ... 
```

**Comment by anajens** [comment]
Adding some notes from discussion today: 

- Users can already control row labels, so there is little concern that the row label width will be too wide in the header.
- For large tables, it would be OK to repeat the table header on each page in the row and column space

**Comment by waddella** [comment]
Lets change the `visible_label` argument to `label_position` which can take on the values `c("inline", "topleft", "none")`. Note this will not change the paths to the cells. And, we will deprecate the `visible_label` argument and remove it in an upcoming release.

**Comment by waddella** [comment]
please branch off of `devel` and not `gabe_table_tree_work`

**Comment by gmbecker** [comment]
So I have this working in a feature branch currently, but there is one major design decision remaining, which is what the default behavior should be.

The default behavior previously was to not display variable labels (ie not give them their own rows) unless explicitly asked to. Now we can generalize that to always putting it on the top left, but I'm wondering if we should? Thoughts @waddella @anajens

**Comment by anajens** [comment]
@gmbecker are the updates only related to labels for variables used with `split_rows_by`? If that's the case, I don't have a strong preference on the default behaviour.

Two questions: what is the interaction between labels in the header created `by split_rows_by` and 
 - .. labels created with `append_varlabels`?
 - ...labels in the header created by `analyze / summarize_row_groups` ? (even thought this feature may not be implemented yet)

**Comment by gmbecker** [comment]
> @gmbecker are the updates only related to labels for variables used with `split_rows_by`? 

it will apply to anything that is used in `split_rows_by_*` so the cut-of-a-continuous-variable ones would be covered as well.

> 
> Two questions: what is the interaction between labels in the header created `by split_rows_by` and
> 
> * .. labels created with `append_varlabels`?

So right now they will be interspersed in the exact order they happen during layouting. Any manual appends that occur after layouting (ie by doing it to the full table) will appear at the end.

Its important to note that the indenting that the ones that come from variable labels is based _only_ on  the position of the corresponding split within the layout, not on any previously manually appended values.

> * ...labels in the header created by `analyze / summarize_row_groups` ? (even thought this feature may not be implemented yet)

It does not make sense to do this with summarize_row_groups as far as I can tell, if you have something specific in mind we can discuss it on monday or sometime in the future.

As for analyze, it will work the same way except there is an additional option for the default inline labeling behavior (ie  visible only if there are more than one)
