### ISSUE TITLE
`.in_ref_row` variable passed to `analyze` & co.

### ISSUE THREAD

**Issue by anajens** [Roche/rtables#165]
Issue originally reported by @danielinteractive 

It would be good to have something like a `.in_ref_row` variable populated that the user can define when defining a row split, similarly as we have `.in_ref_col` for column split. 

Examples:

(1) If we summarize change from baseline ("CHG" variable), we don't want to have 0s displayed when being in the reference row, i.e. baseline visit here:

```r
library(rtables)
library(dplyr)

anl <- ex_adlb %>%
  filter(PARAMCD == "ALT") %>%
  filter(AVISIT != "SCREENING")

basic_table() %>%
  split_cols_by("ARM") %>%
  split_rows_by("AVISIT", split_fun = drop_split_levels) %>%
  analyze("CHG") %>%
  build_table(anl)
```

```
                A: Drug X   B: Placebo   C: Combination
-------------------------------------------------------
BASELINE                                               
  Mean              0           0              0       
WEEK 1 DAY 8                                           
  Mean            -0.97        0.14           0.2      
WEEK 2 DAY 15                                          
  Mean            -0.16       -0.06          -2.41     
WEEK 3 DAY 22                                          
  Mean            0.69        -0.63          -2.05     
WEEK 4 DAY 29                                          
  Mean            1.13        -1.04          -1.25     
WEEK 5 DAY 36                                          
  Mean            1.26        -0.59          -0.92 
```

Proposed code:
```r
basic_table() %>%
  split_cols_by("ARM") %>%
  split_rows_by("AVISIT", ref_level = "BASELINE") %>%
  analyze("CHG", afun = function(x, .in_ref_row) `if`(.in_ref_row, "", mean(x))) %>%
  build_table(anl)
```

```
                A: Drug X   B: Placebo   C: Combination
-------------------------------------------------------
BASELINE                                               
  Mean                                                 
WEEK 1 DAY 8                                           
  Mean            -0.97        0.14           0.2      
WEEK 2 DAY 15                                          
  Mean            -0.16       -0.06          -2.41     
WEEK 3 DAY 22                                          
  Mean            0.69        -0.63          -2.05     
WEEK 4 DAY 29                                          
  Mean            1.13        -1.04          -1.25     
WEEK 5 DAY 36                                          
  Mean            1.26        -0.59          -0.92 
```

**Comment by gmbecker** [comment]
So row splits don't have the concept of a baseline/reference group, primarily because they do not have the ability to do automatic comparisons (values in one row group are not available at tabulation time to values within another row group, whereas they are for columns within a single row group).

Given that that is the case, and unlikely to change, would this function still be useful? @anajens @danielinteractive

**Comment by danielinteractive** [comment]
Thanks @gmbecker for having a look at this - I think it could still be useful. 
And actually I do remember that we had a table where we would need row comparisons. Somehow I can't find it right now though. @anajens do you remember?
For now of course we can put this on the back of the priority lists. But I can very well imagine that the row comparison topic might come up soon when working with other partners who have different table conventions than we have. So it might be worth thinking ahead about this one.

**Comment by anajens** [comment]
We discussed that https://github.com/Roche/rtables/issues/184 may be able to solve this.

**Comment by waddella** [comment]
I moved it to the blocked column in hope that #184 solves it

**Comment by anajens** [comment]
Today @gmbecker suggested a solution for the simple mockup above where the conditional row formatting can be applied selectively in analysis functions based on `prev_splvals` data frame (feature under development). 

The more complex version of this mockup requires access to reference rows data in order to compute some statistics. Here's an example mockup:

![image](https://user-images.githubusercontent.com/43623360/129819636-0609d8c8-3e44-41f8-b22a-665d57b64c6a.png)

@gmbecker what do you think about an approach where we use a custom split function which can deliver both reference row data and analysis row data at each split level to the analysis function?

**Comment by waddella** [comment]
This is a difficult feature due to design choices. The work-around is to use `.spl_context` and get the comparison data via scoping from the full data.

Note also that for row-space references it becomes a more difficult task for specification as parent nodes have data, i.e. there are many possible reference in the hierarchy.

If this request comes repeatedly up then please reopen the issue and discuss it.
