### ISSUE TITLE
Enhance pruning function to be able to subset rtable in a customized way, i.e. by paths

### ISSUE THREAD

**Issue by bahatsky** [Roche/rtables#181]
There are situations, for example, for the table below that shows number of patients by toxicity grade when not all the levels of the table are clinically meaningful, i.e. lab test can only have one direction of abnormality. In this case displaying it in the table doesn't make sense, but also pruning or trimming the rtable is not an option as it will remove sections with zeroes that are meaningful as well. It would be helpful to have a customized way to subset rtable objects to be able to address the questions from the stakeholders in the best way, since not everything can be handled via layout. For this example the way to subset would be to create a dataframe with PARAMCDs and abnormality directions that make sense and then use it to compare with the content of rtable.
I have included an example where for ALT low abnormality direction is not "possible".
```r
source("https://raw.github.roche.com/NEST/nest_on_bee/master/bee_nest_utils.R")
bee_use_nest(release = "2021_03_22")
library(dplyr)
library(random.cdisc.data)
library(rtables)
library(tern)

adsl <- radsl(cached = TRUE)
adlb <- radlb(cached = TRUE) %>%
  var_relabel(WGRLOFL = "Direction of Abnormality")

# Ensure character variables are converted to factors and empty strings and NAs are explicit missing levels.
adsl <- df_explicit_na(adsl)
adlb <- df_explicit_na(adlb)

adlb_f <- adlb %>%
  dplyr::filter(!AVISIT %in% c("SCREENING", "BASELINE")) %>%
  dplyr::mutate(
    ATOXGR = as.numeric(as.character(ATOXGR)),
    WGRLOFL = case_when(WGRLOFL == "Y" ~ TRUE, TRUE ~ FALSE),
    WGRHIFL = case_when(WGRHIFL == "Y" ~ TRUE, TRUE ~ FALSE),
  #remove low direction for ALT
    ATOXGR1=case_when(ATOXGR>0 ~ ATOXGR,ATOXGR<=0 & PARAMCD!="ALT"~ATOXGR,ATOXGR<=0 & PARAMCD=="ALT"~0),
    WGRLOFL1 = case_when(PARAMCD!="ALT"~WGRLOFL, TRUE ~ FALSE),
    
  ) %>%
  droplevels()

lyt <- basic_table() %>%
  split_cols_by("ARMCD") %>%
  add_colcounts() %>%
  split_rows_by("PARAMCD") %>%
  summarize_num_patients(
    var = "USUBJID",
    required = "ATOXGR1",
    .stats = "unique_count"
  ) %>%
 
  count_abnormal_by_worst_grade(
    "ATOXGR",
    abnormal = c(Low = "low",High="high"),
    variables = list(id = "USUBJID", worst_grade_flag = c(Low = "WGRLOFL1", High="WGRHIFL"))
  ) %>%
  append_topleft("Direction of Abnormality") %>%
  append_topleft("  Highest NCI CTCAE Grade")

result <- build_table(
  lyt = lyt,
  df = adlb_f,
  alt_counts_df = adsl
)
result



```

**Comment by bahatsky** [comment]
![Screenshot 2021-04-16 140507](https://user-images.githubusercontent.com/82655520/115021950-f5371480-9ebc-11eb-86ee-6a9c3bc36921.png)

**Comment by gmbecker** [comment]
@bahatsky please see #109 and my comments when closing it, as I believe what you are describing is the same as the ask there. If so, you will find the solution in my response.

I'm closing this issue as a duplicate, please reopen if I'm incorrect and the solution to #109 does not cover your usecase

**Comment by bahatsky** [comment]
Hi @gmbecker! I tried implementing your function for the standard layouts we use in pharma and it's not that easy since some of our internal functions don't allow any additional parameters like split_fun. So this would work for a case when we have several split_rows_by calls, but not in all the cases. It would be great to be able to post-process the rtables object instead of finding a solution for every single layout function. What to you think?

**Comment by gmbecker** [comment]
So @bahatsky I'm not aware of what internal functions you are talking about. The point I am making is that if that kind of pruned tree is what you want, is what those functions should be giving, then that is/will be the canonical way to do that.

You can also customize pruning. You can give it a function which accepts an element in a table tree and returns TRUE or FALSE, TRUE meaning it remains int he table, FALSE meaning it will be pruned (removed).

That is pretty advanced usage but it is supported fully.

**Comment by bahatsky** [comment]
Hi @gmbecker would you mind providing an example of this? Something that I would be able to play with internally?

**Comment by gmbecker** [comment]
You can see the pruning functions that rtables ships with. They are found
in R/tt_compare_tables.R

**Comment by bahatsky** [comment]
Hi @gmbecker I am not sure there's the example I am looking for. So let's say I want to remove the rows like in #109  but after the rtable has been created, not in the layout set up. How would I do that?

**Comment by gmbecker** [comment]
So I mean, you can't easily. Not for multiple constraints. Thats why the correct way to do this. Conceptually the constraints are in the splitting.

So if my job depended on me doing what you're describing in the version of rtables you have access to, what IW ould do is

```{r}
rdf <- make_row_df(tbl)
## code here to subset rdf based on the path (list) column
keeprdf <- fancy_subset_fun(rdf, map)
trimtbl <- tbl[keeprdf$abs_rownumber, ]
```
Again though, that should really only be considered a work around until the layouting functions you are referring to  are updated to implement this in the splitting. There are a few reasons for this, but the most obvious one is that generating many many rows you already know you don't want and then taking them back out is going to be extremely inefficient compared to not creating them at all.

For completeness I will also say that in code I am about to push to gabe_tabletree_work, you can also do 
```
tt_at_path(tbl, c("my", "path", "to", "remove")) <- NULL
```
To remove a sub-element ( and all its children).

**Comment by bahatsky** [comment]
Subsetting by path would be perfect! Could you please let me know when you push where I should look for it?

**Comment by bahatsky** [comment]
Hi @gmbecker , have you pushed that code yet?
