### ISSUE TITLE
gt render function

### ISSUE THREAD

**Issue by waddella** [Roche/rtables#192]
It would be good to have a export/render function to a `gt` object so that `rtables` can be rendered in formats such as doc and rtf. This will address the issue #16 originally submitted by @elong0527.

**Comment by gmbecker** [comment]
@waddella looking at this, it doesn't seem possible to do this in the general case. In particular it looks like gt only supports one level of structural nesting in column space via the column "spanning labels". So we can output gt tables when the there are 0, 1, or 2 column splits, but not if there are 3+.

I'm not sure if its better to support it for some tables and get users used to it working but then say  "well you're out of luck with thtat table its impossible" when they try it with an unsupported table, or to not give the feature at all.

**Comment by gmbecker** [comment]
Closing this as we will not be doing this, but have other things in place (flextable) or coming in this vein
