### ISSUE TITLE
Tables in Viewer are difficult to read

### ISSUE THREAD

**Issue by anajens** [Roche/rtables#194]
I'm testing `gabe_table_tree` branch and noticed that the Viewer output looks different. 
- Columns are too crowded, there needs to be some cell padding
- I think we need at least a line to separate the header from the body of the table so it's easier to read
![image](https://user-images.githubusercontent.com/43623360/117350170-3c8c4180-ae7a-11eb-8780-a144b228c9c2.png)

This is how it looks with rtables `devel`  verison:
![image](https://user-images.githubusercontent.com/43623360/117350091-254d5400-ae7a-11eb-8fa1-4cab96fd7fa4.png)

**Comment by gmbecker** [comment]
Hmm, I don't know why this would be. @waddella has the viewer code been touched?

Anyway, thanks for the report, we will look into this.

**Comment by anajens** [comment]
Also the nice indentation in the header is lost: 
![image](https://user-images.githubusercontent.com/43623360/117355538-b58e9780-ae80-11eb-87b6-ea4121683339.png)

![image](https://user-images.githubusercontent.com/43623360/117355565-c17a5980-ae80-11eb-9e4c-7386571b106d.png)

**Comment by npaszty** [comment]
@gmbecker 
in addition to these observations here is another permutation related to as_html().

From randomly generated data.
![image](https://user-images.githubusercontent.com/40777373/118163494-e584f000-b3d6-11eb-98ef-047e4ec44aea.png)

While not in the open source environment we also see some challenges when using in our shiny app framework. perhaps this also could be looked into.
![image](https://user-images.githubusercontent.com/40777373/118163833-4b717780-b3d7-11eb-9d34-1a122c7bafc9.png)

**Comment by svoicugit** [comment]
From what I noticed, the html css classes are missing, hence the formatting is off...

**Comment by gmbecker** [comment]
@svoicugit was correct, this is a bug that was introduced during my work on #168, but that wasn't caught because I never use `Viewer` and we don't currently have any tests for `as_html`.

Luckily it was also a very easy fix. Things should work now in versions 0.3.7.006+ (pushed to devel).

**Comment by anajens** [comment]
Thank you very much for the fix @gmbecker!
