### ISSUE TITLE
documentation: label_pos

### ISSUE THREAD

**Issue by anajens** [Roche/rtables#196]
Please update docs for `label_pos` argument in `split_rows_by`.  Currently it says that "default" is accepted, but it is not. 

This is in `gabe_tabletree_work ` branch.

**Comment by gmbecker** [comment]
Documentation across the whole package now has:

```
label_pos: character(1). Location the variable label should be
          displayed, Accepts hidden (default for non-analyze row
          splits), visible, topleft, and - for analyze splits only -
          default.  For analyze calls, ‘default’ indicates that the
          variable should be visible if and only if multiple variables
          are analyzed at the same level of nesting.
```

@anajens please feel free to reopen if  you feel that still isn't sufficiently clear.
