### ISSUE TITLE
Multiple Header Rows

### ISSUE THREAD

**Issue by dgkf** [Roche/rtables#2]
# Motivation
Often tables are used to communicate multiple types of information that my not all be described by the same headers despite all being connected by the same source of information or summarizing groups. 

Although the argument could be made for splitting this into two tables, it's often a pain to keep two separate tables consistently formatted and aligned. It can be much easier to keep them as one collective object with shared stylistic attributes. Joining the tables also communicates that they both speak to a cohesive narrative or argument.

In the spirit of accommodating that style of communication, would it be possible to extend the API to allow for multiple header rows?

# Example:

<table>
  <tr>
    <td><strong>Transmission</strong></td>
    <td align="center"><strong>Average MPG</strong></td>
    <td align="center"><strong>SD MPG</strong></td>
  </tr>
  <tr>
    <td>Automatic</td>
    <td align="center">31.25</td>
    <td align="center">4.87</td>
  </tr>
  <tr>
    <td>Manual</td>
    <td align="center">34.98</td>
    <td align="center">3.56</td>
  </tr>
  <tr>
    <td><strong># Carburetors</strong></td>
    <td colspan=2 align="center"><strong>N (NAs)</strong></td>
  </tr>
  <tr>
    <td>4</td>
    <td colspan=2 align="center">28 (3)</td>
  </tr>
  <tr>
    <td>5</td>
    <td colspan=2 align="center">21 (2)</td>
  </tr>
  <tr>
    <td>6</td>
    <td colspan=2 align="center">16 (3)</td>
  </tr>
  <tr>
    <td>8</td>
    <td colspan=2 align="center">2 (0)</td>
  </tr>
</table>

**Comment by waddella** [comment]
The html code for your example table does not use `th` for the header and hence it is not explicit what is a header and what is not. If row 1 and row 4 are header rows and the rest are body rows then that would require careful thought when implementing pagination. For `rtables` pagination will be a key feature. Do you have any suggestions how you would paginate the above table?

Currently `rtables` can already make a similar table with the version on the `devel` branch:

```r
rtable(
  header = rheader(
    rrow("Transmission", "Average MPG", "SD MPG")
  ),
  rrow("Automatic", 31.25, 4.87),
  rrow("Manual", 34.98, 3.56),
  rrow("# Carburetors", rcell("N (NAs)", colspan = 2)),
  rrow("4", rcell(c(28, 3), format = "xx.xx (xx.xx)", colspan = 2)),
  rrow("5", rcell(c(21, 2), format = "xx.xx (xx.xx)", colspan = 2)),
  rrow("6", rcell(c(16, 3), format = "xx.xx (xx.xx)", colspan = 2)),
  rrow("8", rcell(c(2, 0), format = "xx.xx (xx.xx)", colspan = 2))
)
```
This is not perfect, but once we add more formatting capabilities then it would become possible to create the above table.
