### ISSUE TITLE
Deprecate insert_rrow support for TableTree objects?

### ISSUE THREAD

**Issue by gmbecker** [Roche/rtables#214]
When analyzing the behavior in #202 a number of problematic corner cases for `insert_rrow` in non-trivial tables occurred to me. While we can easily continue to support `insert_rrow` for `ElementaryTable` objects, its not clear we can in the general case in a way that is both coherent and likely to be useful rather than confusing to the user.

# Ambiguities

## LabelRow in position that does not correspond to a substructure

Currently this works, and a labelrow is placed whre a DataRow would have been, but I am fairly confident this is ultimately a broken table structure. Even if it is not, it is will make retrieving the cell values of the table or subtable not have the expected dimensions.

## LabelRow in a position where multiple subtables with non-visible label rows are present between two visible rows.

This is ambiguous. We could choose to always do minimum depth or always maximum depth from amongst the options, but those will have very different resulting indentation structures and its not clear one or the other is always what the user will want.

## Label row at a position where a visible label row already exists in the structure

I don't think it should replace the existing label, as this is an insert operation, but if we put it in as a normal child we have the same issues we did above. 

## DataRow in position that spans structural breaks

This is supported now, and is "greedy", ie it will always be the last sibling of the previous row rather than the first sibling of the trailing row corresponding to the position. This is "correct" in that it avoids issues where the trailing row is a label, and thus cannot have a preceeding direct sibling that is a Data row, but it is also not unambiguously what the user is going to want.

There may be others.

Thoughts @anajens @waddella @danielinteractive ?

**Comment by waddella** [comment]
I will check tomorrow in the internal code, if we don’t use it we go immediately ahead and remove it, otherwise we need to discuss the use-case.

**Comment by gmbecker** [comment]
I suspect it is used, as #202 was filed unprompted, but yes we should wait to hear how much, how, and why it is used if it is.

**Comment by danielinteractive** [comment]
@waddella at least on a quick search in tlg-catalog I see quite a few lines of code that use this. So I would recommend checking with @anajens before any large changes here.

**Comment by gmbecker** [comment]
More thoughts here for @anajens as she looks at what the code is doing now.

I think some sort of manual insertion is possible but I feel like it has to be path based to not have major ambiguity problems, so if we deprecate this we would replace it with something along the lines of `insert_at_path` and would error informatively if you requested any of the impossible (Rather than ambiguous) things I mentioned in the issue text. 

@waddella
