### ISSUE TITLE
Missing attributes for layouts with `add_overall_level` 

### ISSUE THREAD

**Issue by anajens** [Roche/rtables#221]
It looks like layouts with `add_overall_level` have empty names:

```
> tbl <- basic_table() %>%
+   split_cols_by("ARM") %>%
+   add_overall_col("ALL") %>%
+   analyze("AGE") %>%
+   build_table(ex_adsl)
> 
> names(tbl)
[1] "" "" "" ""
```

Also, there is a warning when `col_info` is used:
```
An InstantiatedColumnInfo object
Columns:
A: Drug X (ARM)
B: Placebo (ARM)
C: Combination (ARM)
ALL (XXX)

Warning message:
In payloadmsg(spl) :
  don't nkow how to make payload print message for Split of classAllSplit
```

This may be related to https://github.com/Roche/rtables/issues/183.

**Comment by gmbecker** [comment]
The warning is largely unrelated, it is in the printing method for InstatiatedColumnInfo objects, which generally don't get printed in the first place, but it is supported so I will fix that and then close this.
