### ISSUE TITLE
Add github actions CI to gabe_tabletree_work branch

### ISSUE THREAD

**Issue by gmbecker** [Roche/rtables#222]
@dinakar29 @waddella

**Comment by dinakar29** [comment]
@gmbecker - rebasing with `main` should do the trick, unless you're looking to merge `gabe_tabletree_work` into another branch?

**Comment by gmbecker** [comment]
@dinakar29 I just rebased onto main and pushed, I'm still not seeing the actions fire off on push (not just PR)

**Comment by dinakar29** [comment]
Got it. Let me update so that it can fire off a CI build on branch push instead of PR only.

**Comment by dinakar29** [comment]
@gmbecker Updated here: https://github.com/Roche/rtables/commit/00c87f11fb247ab9ffac9ab6dfde0d4508c971ae
Actions run: https://github.com/Roche/rtables/runs/3146710122

**Comment by gmbecker** [comment]
Great thanks. Will reopen if some issue happens but closing for now.

Appreciate the fast turn around.
