### ISSUE TITLE
rtables::var_labels throws an error instead of an empty string for an empty data.frame

### ISSUE THREAD

**Issue by kpagacz** [Roche/rtables#224]
According to the doc string of rtables::var_labels rtables::var_labels returns a named character vector with the variable labels (empty string if not specified), but it returns an error if passed an empty data.frame(). I would expect it to return a character vector of length 0 because an empty data.frame is a valid data.frame with 0 columns and has no variable labels specified.
```r
rtables::var_labels(data.frame()) # throws an error
```

![image](https://user-images.githubusercontent.com/24480246/128015357-f4e99aac-bb8e-4de0-8602-1dca16735253.png)

**Comment by kpagacz** [comment]
As a bonus: there's a typo in the doc string:
![image](https://user-images.githubusercontent.com/24480246/128015985-4c4ca676-964a-4fc0-9dbb-29d3fe88c779.png)

empty string, not **sting**

**Comment by gmbecker** [comment]
Closed as fixed by above commit to formatters
