### ISSUE TITLE
Improve printing of rtables 

### ISSUE THREAD

**Issue by anajens** [Roche/rtables#230]
Issue originally reported by @thomas-neitmann on Jul 15, 2020:

>The current printing of an rtable with the dashed line underneath the header looks rather poor.

```
                            A: Drug X             B: Placebo          C: Combination
                             (N=134)               (N=134)               (N=132)    
------------------------------------------------------------------------------------
Age
  n                            134                   134                   132      
```

>STREAM uses underscores above and below the header as well as after the last line. This is visually much more appealing. Implementing this in rtable.toString() should be fairly easy.

```
____________________________________________________________________________________

                            A: Drug X             B: Placebo          C: Combination
                             (N=134)               (N=134)               (N=132)    
____________________________________________________________________________________

Age
  n                            134                   134                   132      

```

**Comment by gmbecker** [comment]
I'd be fine switching the existing dashed line to underscores (although
they're not centered vertically in the line so that may not actually be
that great). I'm not at all convinced that we should have the top bar when
there are no titles present. That I'm not sure I like. We can discuss it
though.

**Comment by gmbecker** [comment]
This is done in both main and gabe_tabletree_work
