### ISSUE TITLE
expand output formats

### ISSUE THREAD

**Issue by anajens** [Roche/rtables#232]
Originally reported by @kieranjmartin on Apr 30, 2021

> In general, it would be good to expand the as_ methods to cover the following:
> 
> - as_csv
> - as_md
> - as_pdf (maybe unecessary if you have as_md as the user can just use rmd to do it, but potentially helpful)
> - as_tibble/as_data.frame
> - 
> Less core ideas that could be useful for transmitting/modifying information
> 
> - as_json
> - as_xml

**Comment by gmbecker** [comment]
The issue with most of these is the same as with flextable. A tibble/csv/md
table cannot have nested column structures in a meaningful way, so what
those `as_*` functions would do will need to be discussed, as it is not
obvious

**Comment by gmbecker** [comment]
We now have a (lossy) tibble/tsv conversion and a non-lossy pdf conversion. No current plants to do an md since we have HTML already, and xml is a duplicate, so closing this issue.
