### ISSUE TITLE
it would be nice if `rbind(tab)` does not fail but just returns `tab`

### ISSUE THREAD

**Issue by danielinteractive** [Roche/rtables#254]
reprex:
```r
library(rtables)
mtbl <- rtable(
  header = rheader(
    rrow(row.name = NULL, rcell("Sepal.Length", colspan = 2), rcell("Petal.Length", colspan=2)),
    rrow(NULL, "mean", "median", "mean", "median")
  ),
  rrow(
    row.name = "All Species",
    mean(iris$Sepal.Length), median(iris$Sepal.Length),
    mean(iris$Petal.Length), median(iris$Petal.Length),
    format = "xx.xx"
  )
)
rbind(mtbl)
```

observation:
`Error in rbind2(..1) : no method for coercing this S4 class to a vector`

expected behavior:
just return `mtbl`, in the same way as e.g. work `rbind(matrix(1, 1, 1))` et al.

motivation:
this can help when having a list of tables to be `rbind`ed but not being sure that there is more than 1 element in it. 

session info:
```
R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux

Matrix products: default
BLAS/LAPACK: /usr/lib64/libopenblas-r0.3.3.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rtables_0.3.8.9002 magrittr_2.0.1    

loaded via a namespace (and not attached):
[1] compiler_4.0.3  fastmap_1.1.0   htmltools_0.5.2 tools_4.0.3     yaml_2.2.1     
[6] grid_4.0.3      digest_0.6.28   rlang_0.4.11    
```

**Comment by gmbecker** [comment]
I have done this in the latest commit (referenced above) though I consider it experimental for now. 

Note that this emans you can't reason about structure of what comes out of rbind as easily as you would have been able to. @danielinteractive @waddella, we should talk/think about the implications of that more before this change gets merged anywhere.

**Comment by danielinteractive** [comment]
Thanks @gmbecker - since I am out of the discussions please decide together with @waddella

**Comment by waddella** [comment]
please add a new parent as if there were multiple tables so that the result of `rbind` stays predictable

**Comment by danielinteractive** [comment]
@waddella is this fixed?

**Comment by danielinteractive** [comment]
@gmbecker @waddella can we close this?

**Comment by gmbecker** [comment]
@danielinteractive it now returns a new table with tab as the only child, we decided on this so that rbind always adds the same amount of structure (a new parent) regardless of how many are being rbound.

Closing
