### ISSUE TITLE
Uninformative error message created when user split_cols_by a variable that does not exist in the analysis dataset

### ISSUE THREAD

**Issue by anajens** [Roche/rtables#258]
Originally reported by withycok on 29 Jun 2021.

> When you build a table and you split_cols_by, say ACTARM, and this column is in ADSL (alt_counts_df), but not in the dataset being analysed (df). The error is the following ... From which it is really not clear what is going on.

Example:
```r
library(rtables)
library(dplyr)

df_anl <- ex_adsl %>%
  select(-ARM) %>% #remove arm
  slice(1:10)

df_alt <- ex_adsl

basic_table() %>%
  split_cols_by("ARM") %>%
  analyze("AGE") %>%
  build_table(df_anl, alt_counts_df = df_alt)

```
Error:
```
Split var [ARM] was not character or factor. Converting to factor
Error: Assigned data `varvec` must be compatible with existing data.
x Existing data has 10 rows.
x Assigned data has 0 rows.
ℹ Only vectors of size 1 are recycled.
Run `rlang::last_error()` to see where the error occurred.
```

**Comment by gmbecker** [comment]
Fixed in the above commit with stricter unit tests that check for the correct error instead of just any error in this case.
