### ISSUE TITLE
[Listings prototype feedback] adding format to column with NAs results in error

### ISSUE THREAD

**Issue by anajens** [Roche/rtables#260]
Feedback based on https://github.com/Roche/rtables/issues/176#issuecomment-961542251 with 

> packageVersion("rtables")
[1] ‘0.4.0.3’

```r
library(rtables)
library(dplyr)

anl <- ex_adsl %>%
  select(USUBJID, ARM, BMRKR1) %>%
  slice(1:10)

anl$BMRKR1[1:3] <- NA

# (1) Error with NA values in numeric column when apply format
lsting <- as_listing(anl, key_cols = c("ARM", "USUBJID")) %>%
  add_listing_col("ARM") %>%
  add_listing_col("USUBJID") %>%
  add_listing_col("BMRKR1", format = "xx.xx") 

mat <- listing_matrix_form(lsting)
cat(toString(mat))
```

Error is:
```
 Error in (function (x, n, just = c("center", "left", "right"))  : 
  n needs to be numeric and > 0 
```

```r
# NAs in formats work OK for tables:
basic_table() %>%
  split_cols_by("ARM") %>%
  analyze("BMRKR1", afun = mean, inclNAs = TRUE, format = "xx.xx") %>%
  build_table(anl)
```

```
       A: Drug X   B: Placebo   C: Combination
----------------------------------------------
mean      NA          5.97            NA      
```

**Comment by gmbecker** [comment]
A note here @anajens @waddella what is the desired behavior for NAs in a listing? `"NA"` or printing an empty cell/dash?

Any of these are easy to do, as I have identified the problem, but since we are moving away from supporting functions, it will only be able to be one of them

**Comment by anajens** [comment]
@gmbecker I don't have a strong preference. STREAM behaviour is to print an empty cell. But "NA" would also be ok since it's more explicit.

**Comment by waddella** [comment]
moved to https://github.com/insightsengineering/rlistings/issues/5
