### ISSUE TITLE
[Listing prototype feedback] labels not displayed for factor key columns

### ISSUE THREAD

**Issue by anajens** [Roche/rtables#261]
Feedback based on https://github.com/Roche/rtables/issues/176#issuecomment-961542251 with 

> packageVersion("rtables")
[1] ‘0.4.0.3’

The label for USUBJID2 is not displayed when this column is used as a key column.
```r
library(rtables)
library(dplyr)

anl <- ex_adsl %>%
  select(USUBJID, ARM, BMRKR1) %>%
  slice(1:10) %>%
  mutate(
    USUBJID2 = factor(USUBJID)
  ) %>%
  arrange(USUBJID) %>%
  var_relabel(USUBJID2 = "Patient ID")

var_labels(anl)

lsting <- as_listing(anl, key_cols = c("USUBJID", "USUBJID2")) %>%
  add_listing_col("ARM") %>%
  add_listing_col("BMRKR1", format = "xx.x")
lsting

```

![image](https://user-images.githubusercontent.com/43623360/140821504-a2bb812f-2711-429a-b0f5-fef607c4f1b9.png)

**Comment by gmbecker** [comment]
Fixed in the above commit.
