### ISSUE TITLE
[Listing prototype feedback] labels with line breaks not fully shown in key columns

### ISSUE THREAD

**Issue by anajens** [Roche/rtables#262]
Feedback based on https://github.com/Roche/rtables/issues/176#issuecomment-961542251 with 

> packageVersion("rtables")
[1] ‘0.4.0.3’

```r
library(rtables)
library(dplyr)

anl <- ex_adsl %>%
  select(USUBJID, ARM, BMRKR1) %>%
  slice(1:10) %>%
  arrange(USUBJID) %>%
  var_relabel(
    USUBJID = "Unique\nSubject\nIdentifier",
    ARM = "Description\nOf\nPlanned Arm"
  )

var_labels(anl)

lsting <- as_listing(anl, key_cols = c("USUBJID")) %>%
  add_listing_col("ARM")
lsting

```

![image](https://user-images.githubusercontent.com/43623360/140822736-e61c4b52-980e-4620-897e-75beb50c906f.png)

**Comment by gmbecker** [comment]
This was actually a  regression related to top-left display introduced as I continue to consolidate the printing machinery across tables and listings.  Fixed in the above commit with a regression test.
