### ISSUE TITLE
pag_tt_indices is not counting line breaks

### ISSUE THREAD

**Issue by clarkliming** [Roche/rtables#277]
pag_tt_indices is not counting any line breaks

```{r}
aa = rtable(
  header = c('a','b'),
  rrow('', 1, 'abcd\nefgd\nasda'),
  rrow('', 2, 'dasd\nasda\nasda'),
  rrow('', 3, 'dasd\nasda\nasda'),
  rrow('', 4, 'dasd\nasda\nasda'),
  rrow('', 5, 'dasd\nasda\nasda'),
  rrow('', 6, 'dasd\nasda\nasda'),
  rrow('', 7, 'dasd\nasda\nasda'),
  rrow('', 8, 'dasd\nasda\nasda'),
  rrow('', 9, 'dasd\nasda\nasda')
)
aa[pag_tt_indices(aa, 10)[[1]],]
```
apparently there are too much lines in the table. I can see that `nlines` function is not used in `make_df_row` and all rows are treated as one line content.
─ Session info ───────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.3 (2020-02-29)
 os       Red Hat Enterprise Linux    
 system   x86_64, linux-gnu           
 ui       X11                         
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       Europe/Zurich               
 date     2021-12-14                  

─ Packages ───────────────────────────────────────────────────────────────────
 package      * version    date       lib source                             
 abind          1.4-5      2016-07-21 [3] CRAN (R 3.6.3)                     
 assertthat     0.2.1      2019-03-21 [3] CRAN (R 3.6.3)                     
 backports      1.1.5      2019-10-02 [3] CRAN (R 3.6.3)                     
 boot           1.3-24     2019-12-20 [3] CRAN (R 3.6.3)                     
 broom          0.5.5      2020-02-29 [3] CRAN (R 3.6.3)                     
 callr          3.4.2      2020-02-12 [3] CRAN (R 3.6.3)                     
 car            3.0-6      2019-12-23 [3] CRAN (R 3.6.3)                     
 carData        3.0-3      2019-11-16 [3] CRAN (R 3.6.3)                     
 cellranger     1.1.0      2016-07-27 [3] CRAN (R 3.6.3)                     
 cli            2.0.2      2020-02-28 [3] CRAN (R 3.6.3)                     
 coda           0.19-3     2019-07-05 [3] CRAN (R 3.6.3)                     
 codetools      0.2-16     2018-12-24 [3] CRAN (R 3.6.3)                     
 colorspace     1.4-1      2019-03-18 [3] CRAN (R 3.6.3)                     
 crayon         1.3.4      2017-09-16 [3] CRAN (R 3.6.3)                     
 curl           4.3        2019-12-02 [3] CRAN (R 3.6.3)                     
 data.table     1.12.8     2019-12-09 [3] CRAN (R 3.6.3)                     
 desc           1.2.0      2018-05-01 [3] CRAN (R 3.6.3)                     
 devtools       2.2.2      2020-02-17 [3] CRAN (R 3.6.3)                     
 dfoptim        2018.2-1   2018-04-02 [3] CRAN (R 3.6.3)                     
 digest         0.6.25     2020-02-23 [3] CRAN (R 3.6.3)                     
 dplyr        * 0.8.5      2020-03-07 [3] CRAN (R 3.6.3)                     
 ellipsis       0.3.0      2019-09-20 [3] CRAN (R 3.6.3)                     
 emmeans        1.4.5      2020-03-04 [3] CRAN (R 3.6.3)                     
 EnableRF     * 0.5.1      2021-11-15 [1] Github (Rpackages/EnableRF@58b23b2)
 estimability   1.3        2018-02-11 [3] CRAN (R 3.6.3)                     
 fansi          0.4.1      2020-01-08 [3] CRAN (R 3.6.3)                     
 filters      * 0.1.1      2021-08-03 [1] Github (Rpackages/filters@3e999a6) 
 forcats        0.5.0      2020-03-01 [3] CRAN (R 3.6.3)                     
 foreign        0.8-76     2020-03-03 [3] CRAN (R 3.6.3)                     
 formats      * 0.1.0      2021-08-25 [1] Github (Rpackages/formats@86e9542) 
 fs             1.3.2      2020-03-05 [3] CRAN (R 3.6.3)                     
 generics       0.0.2      2018-11-29 [3] CRAN (R 3.6.3)                     
 ggplot2      * 3.3.0      2020-03-05 [3] CRAN (R 3.6.3)                     
 git2r          0.26.1     2019-06-29 [3] CRAN (R 3.6.3)                     
 glue           1.3.1      2019-03-12 [3] CRAN (R 3.6.3)                     
 gridExtra      2.3        2017-09-09 [3] CRAN (R 3.6.3)                     
 gtable         0.3.0      2019-03-25 [3] CRAN (R 3.6.3)                     
 haven          2.2.0      2019-11-08 [3] CRAN (R 3.6.3)                     
 hms            0.5.3      2020-01-08 [3] CRAN (R 3.6.3)                     
 htmltools      0.4.0      2019-10-04 [3] CRAN (R 3.6.3)                     
 labeling       0.3        2014-08-23 [3] CRAN (R 3.6.3)                     
 lattice        0.20-40    2020-02-19 [3] CRAN (R 3.6.3)                     
 lifecycle      0.2.0      2020-03-06 [3] CRAN (R 3.6.3)                     
 lme4           1.1-21     2019-03-05 [3] CRAN (R 3.6.3)                     
 lmerTest       3.1-1      2019-12-13 [3] CRAN (R 3.6.3)                     
 magrittr     * 1.5        2014-11-22 [3] CRAN (R 3.6.3)                     
 MASS           7.3-51.5   2019-12-20 [3] CRAN (R 3.6.3)                     
 Matrix         1.2-18     2019-11-27 [3] CRAN (R 3.6.3)                     
 memoise        1.1.0      2017-04-21 [3] CRAN (R 3.6.3)                     
 minqa          1.2.4      2014-10-09 [3] CRAN (R 3.6.3)                     
 multcomp       1.4-12     2020-01-10 [3] CRAN (R 3.6.3)                     
 munsell        0.5.0      2018-06-12 [3] CRAN (R 3.6.3)                     
 mvtnorm        1.1-0      2020-02-24 [3] CRAN (R 3.6.3)                     
 nlme           3.1-145    2020-03-04 [3] CRAN (R 3.6.3)                     
 nloptr         1.2.2      2020-02-29 [3] CRAN (R 3.6.3)                     
 numDeriv       2016.8-1.1 2019-06-06 [3] CRAN (R 3.6.3)                     
 openxlsx       4.1.4      2019-12-06 [3] CRAN (R 3.6.3)                     
 optimx       * 2020-2.2   2020-02-07 [3] CRAN (R 3.6.3)                     
 pillar         1.4.3      2019-12-20 [3] CRAN (R 3.6.3)                     
 pkgbuild       1.0.6      2019-10-09 [3] CRAN (R 3.6.3)                     
 pkgconfig      2.0.3      2019-09-22 [3] CRAN (R 3.6.3)                     
 pkgload        1.0.2      2018-10-29 [3] CRAN (R 3.6.3)                     
 prettyunits    1.1.1      2020-01-24 [3] CRAN (R 3.6.3)                     
 processx       3.4.2      2020-02-09 [3] CRAN (R 3.6.3)                     
 ps             1.3.2      2020-02-13 [3] CRAN (R 3.6.3)                     
 purrr          0.3.3      2019-10-18 [3] CRAN (R 3.6.3)                     
 R6             2.4.1      2019-11-12 [3] CRAN (R 3.6.3)                     
 Rcpp           1.0.3      2019-11-08 [3] CRAN (R 3.6.3)                     
 readxl         1.3.1      2019-03-13 [3] CRAN (R 3.6.3)                     
 remotes        2.1.1      2020-02-15 [3] CRAN (R 3.6.3)                     
 rio            0.5.16     2018-11-26 [3] CRAN (R 3.6.3)                     
 rlang        * 0.4.5      2020-03-01 [3] CRAN (R 3.6.3)                     
 rprojroot      1.3-2      2018-01-03 [3] CRAN (R 3.6.3)                     
 rtables      * 0.3.8      2021-08-23 [2] local                              
 sandwich       2.5-1      2019-04-06 [3] CRAN (R 3.6.3)                     
 scales         1.1.0      2019-11-18 [3] CRAN (R 3.6.3)                     
 sessioninfo    1.1.1      2018-11-05 [3] CRAN (R 3.6.3)                     
 stringi        1.4.6      2020-02-17 [3] CRAN (R 3.6.3)                     
 stringr      * 1.4.0      2019-02-10 [3] CRAN (R 3.6.3)                     
 survival       3.1-11     2020-03-07 [3] CRAN (R 3.6.3)                     
 tern         * 0.7.4      2021-08-23 [2] local                              
 testthat       2.3.2      2020-03-02 [3] CRAN (R 3.6.3)                     
 TH.data        1.0-10     2019-01-21 [3] CRAN (R 3.6.3)                     
 tibble         2.1.3      2019-06-06 [3] CRAN (R 3.6.3)                     
 tidyr        * 1.0.2      2020-01-24 [3] CRAN (R 3.6.3)                     
 tidyselect     1.0.0      2020-01-27 [3] CRAN (R 3.6.3)                     
 useNEST        1.0.0      2020-12-24 [3] local                              
 usethis        1.5.1      2019-07-04 [3] CRAN (R 3.6.3)                     
 utils.nest     0.2.9      2021-08-23 [2] local                              
 vctrs          0.2.3      2020-02-20 [3] CRAN (R 3.6.3)                     
 viridisLite    0.3.0      2018-02-01 [3] CRAN (R 3.6.3)                     
 withr          2.1.2      2018-03-15 [3] CRAN (R 3.6.3)                     
 xtable         1.8-4      2019-04-21 [3] CRAN (R 3.6.3)                     
 yaml           2.2.1      2020-02-01 [3] CRAN (R 3.6.3)                     
 zip            2.0.4      2019-09-01 [3] CRAN (R 3.6.3)                     
 zoo            1.8-7      2020-01-10 [3] CRAN (R 3.6.3)                     

[1] /home/bceuser/lil128/Trials/YP39364/libraries
[2] /opt/nest/2021_07_07/3.6.3/libs
[3] /opt/mango/R/3.6.3/lib/R/library
---

your brief description of the problem

```r
library(rtables)

# your reproducible example here

```

**Comment by gmbecker** [comment]
This appears to have been fixed (at least in devel, I suspect also in main but don't have it handy right this second), thanks for the report.

Note that there actually is no valid pagination with lpp = 10, because the default is to require 2 preceeding siblings before a pagination, if we change the 10 to 12, though, we get the desired behavior:


```
> paginate_table(aa, 12)
[[1]]
   a    b  
———————————
   1   abcd
       efgd
       asda
   2   dasd
       asda
       asda
   3   dasd
       asda
       asda

[[2]]
   a    b  
———————————
   4   dasd
       asda
       asda
   5   dasd
       asda
       asda
   6   dasd
       asda
       asda

[[3]]
   a    b  
———————————
   7   dasd
       asda
       asda
   8   dasd
       asda
       asda
   9   dasd
       asda
       asda
```
