### ISSUE TITLE
footers on the left hand side

### ISSUE THREAD

**Issue by Polkas** [Roche/rtables#291]
I have an expectation that table footers should be on the middle or right.
Does the current design expected, to have footers only on the left hand side.
This will be more important for bigger tables.

```
library(rtables)
lyt <- basic_table(main_footer = "project", prov_footer = "organization") %>%
    analyze("AGE", afun = mean)

build_table(lyt, DM)
#             all obs     
#-----------------------
#mean   34.2219101123596
#-----------------------
#
#project
#organization
```

**Comment by gmbecker** [comment]
Hi @Polkas 

Currently we do not have alignment controls implemented for title or footer materials (of any of the various flavors), so as it stands yes the footer will always be left aligned. 

We can add this to the roadmap, but can you explain to me a little bit more why different alignments for the footer materials will be important for bigger tables?

Thanks for the report and your thoughts

**Comment by Polkas** [comment]
Thank you for your response. 
This is not a crucial functionality in my opinion.
More than that I find out sb could use `rtables::as_html` and then a trivial `css` rule to achieve custom table styling.
A css example:
```
.rtables-footers-block {
  text-align: right;
}
```
