### ISSUE TITLE
Consider moving rowname formatting to cell formatting parameters

### ISSUE THREAD

**Issue by dgkf** [Roche/rtables#3]
Currently, the `row.name` argument has no default in `rrow()`, and it's only possible to remove its behavior by passing NULL to the `row.name` parameter.

Instead of making this functionality a core argument, I'd propose keeping rrows quite detached from their contents and instead format row labels in the table via formatting parameters to the left most column of cells. 

Likewise, `tibbles` do not support row names, meaning that while using many tidyverse functions (which silently coerce dataframes to tibbles) to process a dataframe from which to construct an rtable, one would have to convert back to a data.frame in order to use data.frame row.names to build the table.

**Comment by waddella** [comment]
Thanks for the comment, I will revisit that topic in the next redesign round.

**Comment by gmbecker** [comment]
Closing as this is no longer relevant to the new rtables API
