### ISSUE TITLE
Update staged.deps

### ISSUE THREAD

**Issue by nikolas-burkoff** [Roche/rtables#304]
Hi - can you create a branch named 130_reorg@main and replace the downstream dependency on teal.devel with  teal.widgets please - i.e. replace:

```
    insightsengineering/teal.devel:
    repo: insightsengineering/teal.devel
    host: https://github.com
```

with 
```
  insightsengineering/teal.widgets:
    repo: insightsengineering/teal.widgets
    host: https://github.com
```

And then when the rest of the merge is ready we can merge this PR in.

The right answer is  (?) for NEST to have rtables as an external dependency not an internal one but in the mean time, there may be questions like this.

@gmbecker - can you do this and maybe add branch creation rights to some of the NEST developers?

**Comment by pawelru** [comment]
already done
