### ISSUE TITLE
Empty levels missing when reference column is set

### ISSUE THREAD

**Issue by gmbecker** [Roche/rtables#323]
Hi @gmbecker, I think it is an issue with `VarLevWBaselineSplit`, i.e.

```r
library(rtables)


df <- data.frame(
  val = 1:10,
  grp = factor(rep("a", 10), levels = c("a", "b"))
)
```

And 
```r
basic_table() |>
  split_cols_by("grp") |>
  analyze("val") |>
  build_table(df)
```

results in 

```
        a     b 
————————————————
Mean   5.50   NA
```

and
```r
basic_table() |>
  split_cols_by("grp", ref_group = "a") |>
  analyze("val") |>
  build_table(df)
```

results in 

```
        a  
———————————
Mean   5.50
```

Can you please check that the level with no observation does not get dropped when setting the `ref_group`?

_Originally posted by @waddella in https://github.com/Roche/rtables/issues/322#issuecomment-1128004915_

**Comment by gmbecker** [comment]
So this is interesting. The code is very old (and, I think, not hit very often), but looking now at what is in there, this was at one point intentional. `droplevels` is being called explicitly when the global  child-value-order is determined in the split-that-has-a-reference-group case. 

I think that its ok to remove this. That already happened in the no reference-group case, from the looks of it. In both cases, teh columns are degenerate, but having a reference group doesn't make that *more* wrong in any way that i can think of. Note, however, that this is *technically* a user-facing behavior change, rather than a bugfix.

I'll bring it up in the meeting tomorrow and go ahead and make the change provided there's no pushback.

**Comment by danielinteractive** [comment]
@gmbecker how did the meeting go? can you make the change?

**Comment by gmbecker** [comment]
Yes we will be making the change and it will be in the CRAN release that will be going out in the next couple days.
