### ISSUE TITLE
Fix make_afun example code

### ISSUE THREAD

**Issue by Nolan-Steed** [Roche/rtables#325]
The example code is trying to demonstrate changing the labels of a previous function (`a_foo`) but rather than calling `a_foo2` the example code calls `a_foo`. 

The column displaying `Nrow df` should be changed to `Number of Rows`

![image](https://user-images.githubusercontent.com/56098440/168902329-775f48c0-d363-4089-949f-e30b9d93e21b.png)

**Comment by gmbecker** [comment]
You are absolutely correct. Thank you for the report. I fixed this in the devel version of the documentation (it may take a bit to propogate to the pkgdown site)
