### ISSUE TITLE
Vital sign summary table at baseline (do not want to display change)

### ISSUE THREAD

**Issue by ningxuca** [Roche/rtables#333]
This is a question: Vital sign summary table, for each parameter I want to display raw value, followed by change summary stats at each post baseline visit. However at baseline, I only want to display raw value summary stat. How do I do that? Currently I am seeing all INF or -INF for range

**Comment by gmbecker** [comment]
@ningxuca Its a bit difficult to be specific as you haven't given me a lot of information, but your analysis function can accept the `.in_ref_col` argument (see `?analyze`), which lets allows you to specify different behaviaor in the reference column (provided that was set using `ref_group` in your most deeply nested `split_cols_by` call). This gives you full control to have both content and format be different for your baseline provided it is one of the levels of your column split.

A quick example adapted to what I think you're describing from the `baseline` Vignette:

```
my_afun <- function(x, .ref_group, .in_ref_col) {
    refmean <- mean(.ref_group)
    if(.in_ref_col) { # baseline group
        val <- refmean
        format <- "xx.xx"
    } else {
        val <- c(mean(x),
        (mean(x) - refmean)/refmean)
        format <- "xx.xx (xx.xx%)"
    }
    in_rows(
        "Mean (%diff from baseline)" = rcell(val,
                                             format = format))
}
```
Here we accept both `.ref_group` which will receive the *data* for the reference group, and `.in_ref_col` which tells us if we're in the reference column, and we use that to do what I believe you describe above, roughly:

```
> basic_table() %>%
+   split_cols_by("ARM", ref_group = "B: Placebo") %>%
+     analyze("AGE", afun = my_afun) %>%
+     build_table(DM)
                             B: Placebo     A: Drug X     C: Combination
————————————————————————————————————————————————————————————————————————
Mean (%diff from baseline)     33.02      34.91 (5.72%)   34.57 (4.69%) 
```

Does this answer your question? If not, I'll need more detail about what you're trying and what you want to get.

**Comment by gmbecker** [comment]
@ningxuca did I answer your question? Can this issue be closed?

**Comment by ningxuca** [comment]
Hi Gabe,

Yes. Please close the issue. Thank you so much!

Emily
