### ISSUE TITLE
a way to retrive the current column

### ISSUE THREAD

**Issue by zq2323** [Roche/rtables#342]
Hi @gmbecker , thanks for the great package of table genarator.

I'm wondering if there is a way to get the current column used in the **analyze()** function.  I saw the  argument **.var** can indicate the current analyzing variable, but no **.col** is found here. it will be very convenient to use the split column within **analyze()**.

thank you.

**Comment by zq2323** [comment]
Hi @gmbecker , thanks for you answer.

I'm going to have a survival estimate analyzed.  when the `aval ` being analyzed, how can I pass the values of another variable `cnsr` to the formula based on the current column split?

```
tte <- data.frame(group=c("pat1", "pat2"), time=c(1,2), censor=c(1,0))

ly <- basic_table() %>% 
  split_cols_by("group") %>% 
  analyze("time", afun = function(x){
    
    s <- survfit(Surv(x, censor)~1,
            conf.int = 0.95,
            conf.type = "log-log")
    
  }) %>% build_table(tte)
```

thanks

**Comment by gmbecker** [comment]
If your analysis function accepts `df` instead of `x` as it's first
argument it will retrieve the entire sub-data.frame corresponding with the
faceting you are within.

That should give you what you need if I understand you correctly.

Best,
~G

**Comment by zq2323** [comment]
Oh....my god, how xxx I am, thank you...

**Comment by zq2323** [comment]
And I have another question want to confirm:

When I want custom the value in cell, I try to custom the values in `analyze`:
```
ly <- basic_table() %>% 
  split_cols_by("group") %>% 
  analyze("time",afun = function(x){
    
    cust_value <- paste(1,' (', 1,
                        " ; ", 1,")",
                        sep = "")
    
    ret <- in_rows(
      "Custom value" = rcell(cust_value)
    )
    
    return(ret)
    
  }) %>% build_table(temp)

ly
```

But when I test it in summarize_row_group, it seems an error return, what's the difference here?
```
ly <- basic_table() %>% 
  split_cols_by("group") %>% 
  summarize_row_groups("time",cfun = function(x, labelstr){
    
    cust_value <- paste(1,' (', 1,
                        " ; ", 1,")",
                        sep = "")
    
    ret <- in_rows(
      "Custom value" = rcell(cust_value)
    )
    
    return(ret)
    
  }) %>% build_table(tte)

ly
```

![image](https://user-images.githubusercontent.com/23326363/180717932-76b6a5fe-3e8a-4154-8a49-2faaa5d30c05.png)

**Comment by gmbecker** [comment]
Right, so the hint is in the error message there. By default, content rows
(and thus their cells) have the format "xx (xx.x%)", which requires the
cells to have 2 values (one for the count and one for the percentage).

The format which applies to a cell is always the most specific applicable
one, much like, e.g., CSS styling properties AFAIK. So you want your cell
to have a non-default format so that it won't inherit its format from its
parent (i.e., the row).

If you add `format = "xx"` to your rcell call everything will work.

Best,
~G

**Comment by gmbecker** [comment]
I'm going to go ahead and close this. @zq2323 please feel free to open a new issue if you have further difficulties.
