### ISSUE TITLE
usage of the online repository to apply bootstrap

### ISSUE THREAD

**Issue by Polkas** [Roche/rtables#344]
https://github.com/Roche/rtables/blob/9f116d189ca777a0e65f1bc8a5079f639e1e8279/R/Viewer.R#L41

I think the package could be lighter (inst/bootstrap could be removed) and the solution more elegant if the bootstrap will be loaded from some online repository.

Like:

```
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
```

could be provided with `[htmlDependency](https://rdrr.io/pkg/htmltools/man/htmlDependency.html)`.

**Comment by gmbecker** [comment]
This would cause the viewer, and any other functionality related to viewing or displaying the HTML output to not work when run locally on a machine behinds a firewall or without internet access. 

I don't think that would be a good trade.

**Comment by Polkas** [comment]
I understand the pros and cons, it is of course your decision.

**Comment by gmbecker** [comment]
Thank you for the recommendation but I've decided not to do that, so I'm closing this issue.
