### ISSUE TITLE
Content Information percentage information of c_h_percent not same as rtables

### ISSUE THREAD

**Issue by djhbs** [Roche/rtables#345]
https://github.com/Roche/rtables/blob/a88ec45a7e42b08ef7679dd527f9797081cdc6cd/vignettes/tabulation_dplyr.Rmd#L141-L148

The corrent the percentage information of c_h_percent is not same as the result of rtables.
For subsets `df[df$arm == "Arm A" & df$gender == "Female" & df$country == "CAN" & df$handed == "Left", ]`   
the  results in ratables 33.3%  is   
`nrow(df[df$arm == "Arm A" & df$gender == "Female" & df$country == "CAN" & df$handed == "Left", ]) / nrow(df[df$arm == "Arm A" & df$gender == "Female", ])
` , 
but the results in dplyr  0.711 is  
 `nrow(df[df$arm == "Arm A" & df$gender == "Female" & df$country == "CAN" & df$handed == "Left", ]) / nrow(df[df$arm == "Arm A" & df$gender == "Female" & df$country == "CAN", ])`

The following code can get rigth c_h_percent  same as the rtables
```
df %>%
    group_by(arm, gender, country, handed) %>%
    summarize(mean = mean(age), c_h_count = n()) %>%
    # count by arm, gender, country
    left_join(df %>%
                  group_by(arm, gender, country) %>%
                  summarize(c_count = n())) %>%
    # count by arm, gender
    left_join(df %>%
                  group_by(arm, gender) %>%
                  summarize(n = n())) %>%
    # calculate the percent
    mutate(c_percent = c_count / n,
           c_h_percent = c_h_count / n)
```

**Comment by gmbecker** [comment]
You are absolutely right. Thank you for the report.

I've updated the vignette so that it uses left-joins similarly to how you use them (though not in the same pipeline, for illustrative purposes).
