### ISSUE TITLE
 `main_title` is dropped after the pagination 

### ISSUE THREAD

**Issue by gmbecker** [Roche/rtables#351]
Hi @gmbecker , thanks so much for the quick fix. Another issue with `paginate_table`, it seems that `main_title` was dropped after the pagination (`main_footer` is kept, which is good). Could you split the `main_title` to all pages please. Thanks!

_Originally posted by @shajoezhu in https://github.com/Roche/rtables/issues/350#issuecomment-1208715288_

**Comment by gmbecker** [comment]
This was fixed in the above commit and the regressions that caused check failure have also been subsequently fixed. The latest pushed commit also has a regression test for it

**Comment by shajoezhu** [comment]
Many thanks @gmbecker !
