### ISSUE TITLE
Using analyze() to pass multiple columns to my helper function

### ISSUE THREAD

**Issue by cameronezratty** [Roche/rtables#354]
---

Going off of the introduction to rtables:
https://cran.r-project.org/web/packages/rtables/vignettes/introduction.html

I am setting afun in analyze() equal to myfun() which is a function that I wrote.  myfun() takes two numerical column vectors and does some operation to them.  Lets say it adds them together and then outputs the average of this new vector.  So in this case, we want to make a table of a single value that is the average of all the players age+weight. I can't find a way to pass two columns from the dataframe into myfun().  analyze() takes a character vector of column names but it attempts to do the operation specified to in myfun() to each column name independently rather than using both columns as parameters.  I have tried casting the vars input as a different data type in order to be able to index it but haven't had any luck.

```r
library(rtables)

myfun(x)
     {
         xy = x[[,1]]+x[[,2]]  #This doesnt index the columns correctly
         return(mean(xy))
      }

l <- basic_table() %>%
  analyze(vars = c("age","weight") , afun = myfun, format = "xx.x")

build_table(l, df)


```

**Comment by gmbecker** [comment]
Hi @cameronezratty,

If your afun accepts `df` as its first argument instead of `x`, it will be passed the whole data (sub)set, which will allow you to do what you want
```
> basic_table() %>%
      analyze("AGE", function(df, ...) mean(df[["AGE"]] + df[["BMRKR1"]])) %>% 
      build_table(DM)
          all obs     
——————————————————————
AGE   40.0738583104747
```

Please feel free to reach out with more questions. Closing this one for now.

Best

**Comment by cameronezratty** [comment]
Hi Gabe,


Thank you so much for taking the time to help me out!  I understand your solution and see that it produces the correct result.  I was hoping to produce a solution robust enough such that I can select which two columns to perform afun on in the parameters of analyze and not in the function definition.  I am making lots of tables and want to be able to use the same function and only switch out which two columns I'd like to perform the action on.  For example in your solution below, we are interested in AGE and BMRKR1.  If the next table I am interested in is AGE and a numeric representation of RACE, I would have to rewrite the function.  Is there a way to maybe pass in the columns of interest in the first parameter of analyze() since currently the first parameter of "AGE" is inconsequential in the result.
Please let me know if this is possible or if I should clarify anything.

Thank you again for your help, I appreciate it greatly
-Cameron

**Comment by gmbecker** [comment]
@cameronezratty  There are two ways to do this. The one I prefer aesthetically is to use a function contstructor. `rtables` uses this in various places, e.g., in various provided split functions.

So you can do

```
twovar_mean <- function(second_var) {
    function(df, .var) {
         in_rows(.list = list( mean(df[[.var]] + df[[second_var]])),
                        .names = paste("mean (", .var, "+", second_var, ")"))
    }
}

DM2 <- DM
DM2$BMRKR2 <- rnorm(nrow(DM), 20, 10)
l <- basic_table() %>%
    analyze("AGE", afun = twovar_mean("BMRKR1"), format = "xx.x") %>%
    analyze("BMRKR1", afun = twovar_mean("BMRKR2"), format = "xx.x")
```

```
> build_table(l, DM2)
                             all obs
————————————————————————————————————
AGE                                 
  mean ( AGE + BMRKR1 )       40.1  
BMRKR1                              
  mean ( BMRKR1 + BMRKR2 )    26.8  
```

Alternatively, you can pass the name of your second var as an "Extra argument" to your analysis function

```
twovar_mean2 <- function(df, .var, var2) {
         in_rows(.list = list( mean(df[[.var]] + df[[var2]])),
                        .names = paste("mean (", .var, "+", var2, ")"))
}

l2 <- basic_table() %>%
    analyze("AGE", afun = twovar_mean2, extra_args = list(var2 = "BMRKR1"), format = "xx.x") %>%
    analyze("BMRKR1", afun = twovar_mean2, extra_args = list(var2 ="BMRKR2"), format = "xx.x")
```

```
> build_table(l2, DM2)
                             all obs
————————————————————————————————————
AGE                                 
  mean ( AGE + BMRKR1 )       40.1  
BMRKR1                              
  mean ( BMRKR1 + BMRKR2 )    26.8  
```
