### ISSUE TITLE
Review Vignettes I

### ISSUE THREAD

**Issue by waddella** [Roche/rtables#360]
Please read the following vignettes and try the examples. If you have improvement suggestions create a branch with a PR.

- [x] Introduction to rtables (Davide, )
- [x] Tabulation Concepts
- [ ] Comparison with `dplyr`

**Comment by Melkiades** [comment]
So, before going into the details of these vignettes I think we have to restructure a bit the `README.md`. I have three suggestions for that:

1. **Usage** should show a very concise code with a contained output, just to show the generality of code and output. This is a piece of code that everyone reads and it is the shop window of the software, so it makes sense to use a known and intuitive data set (e.g. `iris`) to highlight the simplicity and generality of Rtables. 
2. More simplicity in the descriptive part of the readme. I think too much text w/o concrete examples could discourage people from actually reading it (e.g. I first tried the example and then read it).
3. Absolutely necessary is a sorted list of vignettes. I found major disorientation in going tentatively about which to do next.

**Comment by Melkiades** [comment]
For the introductory vignette, I have a similar idea as for the readme:

1. The features should be described better and merged in the `README.md` section. Also, competitors should be mentioned, but in a separate vignette that is mentioned in the readme. I saw somewhere an archived issue about comparing timings and so on and I think could be a good place where to have a rosetta-stone kind of things with a proper analysis. I would avoid mentioning this in the intro vignette.
2. The rest I think is quite good (note: there is a bug in the `tibble`-like matrix print). I find though that the chapters are well organized and should be extended with other vignettes they are referred to. For example: **Adding Column Structure** section could have at the end a link to a small vignette with the following functions described with concrete examples where they can be useful. _> in column space: split_cols_by, split_cols_by_cuts, split_cols_by_cutfun, split_cols_by_quartiles_
3. I think the layout instruction should be expanded with more descriptors of it like the very useful `table_structure()` function. Again I would consider adding a link to another vignette with more detail on how the layout is thought and used.

As you can see, I am a supporter of non-linear documentation which I believe is easier to extend and keep as a reference manual than a list of docs.
