### ISSUE TITLE
Add pkgdown publishing to repo automation

### ISSUE THREAD

**Issue by waddella** [Roche/rtables#363]
@cicdguy would you mind doing this? 

If you can add a multi-version documentation that would be awesome, otherwise you can just use the root (CRAN release) and `dev/` (`main`) method that `pkgdown` supports.

**Comment by pawelru** [comment]
I would like to highlight my upvote on this. I can see in GH issues / PRs conversation that some feature has been released but when I enter pkgdown website it was missing. I then realised that pkgdown is outdated and presents old state of the code. This could confuse end-users.
