### ISSUE TITLE
Add vignette on formats precedence and NA handling

### ISSUE THREAD

**Issue by waddella** [Roche/rtables#366]
This will probably also involve documentation additions in formatters in terms of the underlying behavior

**Comment by wwojciech** [comment]
Hi @gmbecker 

During our meeting you advised that it would be good to start working on this by first looking at some specific unit tests and you also showed some specific R file with such tests. I checked all unit test R files in `Roche/rtables` repo but I could not find anyone similar to of that you showed.
Can you pl. remind me where that file you showed is located? Was it maybe https://github.com/insightsengineering/tern/blob/main/tests/testthat/test-formats.R?

Thanks a lot!

**Comment by gmbecker** [comment]
@wwojciech Sorry that wasn't clear, the tests are in formatters [(insightsengineering/formatters)](https://github.com/insightsengineering/formatters/blob/main/tests/testthat/test-formatters.R)
