### ISSUE TITLE
Implement wordwrapping for header/footer materials only

### ISSUE THREAD

**Issue by gmbecker** [Roche/rtables#388]
This should happen during printing (and pagination), not during value assignment

**Comment by shajoezhu** [comment]
Some example 

![image](https://user-images.githubusercontent.com/3692541/189163971-71dc7f72-6150-4c76-ac3f-5a6facf0bad9.png)

**Comment by gmbecker** [comment]
Completed in [756a4b8](https://github.com/Roche/rtables/commit/756a4b80c8334f581a9b936d5105f2341d3415ec)
