### ISSUE TITLE
Visual problem in tibble rendering from all vignettes

### ISSUE THREAD

**Issue by Melkiades** [Roche/rtables#396]
This problem has been there for a bit, and it is possibly a duplicated issue. Here is the rendering on my chrome 105.0.5195.102 (Official Build) (64-bit):
![Screenshot 2022-09-14 145901](https://user-images.githubusercontent.com/11279768/190160903-d39b9c64-8657-4787-8e42-49506b42af15.png)

**Comment by gmbecker** [comment]
Caused by https://github.com/r-lib/pkgdown/issues/2196

Undesirable current workaround is to use `comment="#"`, commit with that inbound.
