### ISSUE TITLE
example in first page readme file gives error, col.names should be changed to header

### ISSUE THREAD

**Issue by armenic** [Roche/rtables#4]
The example in first page readme file gives error:

not all arguments in ... are of class rrow

Changing col.names to header resolves issue. Maybe this is a residue from previous version, but in any case we need to update the page to not distract users. 

Same issue is in:
- compare_rtables examples

**Comment by waddella** [comment]
Hi @armenic,

I am working on an rtables redesign that supports multi line headers hence I have switched the `col.names` argument to `header`. You probably have rtables installed from the branch devel where the `col.names` argument was replaced with `header`. I need to update all the examples once I am ready for the next release.
