### ISSUE TITLE
Summary stats as columns

### ISSUE THREAD

**Issue by vpilliano** [Roche/rtables#407]
Would it be possible to have the summay stats (output of analyze) be arranges as columns rather than rows?

I am referring to something like this below:

![image](https://user-images.githubusercontent.com/91895444/194246146-874c0f81-b831-40fa-8a9b-c5822a89fac2.png)

**Comment by gmbecker** [comment]
You can get this pattern with the combination of `split_cols_by_multivar` and `analyze_colvars`:


```
basic_table() %>%
  split_cols_by_multivar(rep("mpg", 3), varlabels = c("mean", "median", "sd")) %>% 
  split_rows_by("cyl") %>%
  analyze_colvars(afun = list(mean, median, sd)) %>% 
  build_table(mtcars)
Split var [cyl] was not character or factor. Converting to factor
                                                 
                                                 
           mean         median          sd       
—————————————————————————————————————————————————
6                                                
     19.7428571428571    19.7    1.45356704106042
                                                 
                                                 
                                                 
4                                                
     26.6636363636364     26     4.50982765242148
                                                 
                                                 
                                                 
8                                                
           15.1          15.2    2.56004807647164
                                                 
```

**Comment by vpilliano** [comment]
Thanks @gmbecker !

Would it be possible to avoid the new line between the row name and the values?
I mean removing this:

![image](https://user-images.githubusercontent.com/91895444/194292329-2479782a-f50a-459d-b0fc-322d2bd0ab2c.png)

**Comment by Melkiades** [comment]
I do not know how to put it on the same line, but adding ` format = "xx.x"` to `analyze_colvars()` could make it nice (and fix the relevant decimal)

**Comment by gmbecker** [comment]
@vpilliano Generally speaking you cannot put a split label on the same line as an analysis row which is structurally underneath it.

That is a feature which is on the roadmap, but is not in yet.

In the specific case of your table (and not one that is more structurally complex), you can abuse the fact that analysis functions can generate more than one row to get the table you want:

```
mnfun <- function(df, .var) {
    in_rows(.list = tapply(df[[.var]], df$cyl, mean))
}

sdfun <- function(df, .var) {
    in_rows(.list = tapply(df[[.var]], df$cyl, sd))
}

mdfun <- function(df, .var) {
    in_rows(.list = tapply(df[[.var]], df$cyl, median))
}


basic_table() %>%
  split_cols_by_multivar(rep("mpg", 3), varlabels = c("mean", "median", "sd")) %>%
   analyze_colvars(afun = list(mnfun, mdfun, sdfun)) %>%
  build_table(mtcars)
```

```
          mean         median          sd       
————————————————————————————————————————————————
4   26.6636363636364     26     4.50982765242148
6   19.7428571428571    19.7    1.45356704106042
8         15.1          15.2    2.56004807647164
```

**Comment by vpilliano** [comment]
That worked! 

Thank you
