### ISSUE TITLE
`fnotes_at_path<-` functionality is a bit obscure and documentation is partial

### ISSUE THREAD

**Issue by Melkiades** [Roche/rtables#412]
I understand how it works, but I could not find any direct way to access the relevant variables and functionality if not through tests. A small example in the documentation and an explicative way how to describe row and column paths may go a long way here. I recommend binding this with `row_path_summary` and its future (intended) restructuring. 

Update: I found `row_paths` and similar very useful to find and use the path, but still it should be better explained and I have still a cloudy idea of how to cite the content. I will try (copying from tests) to use `@content`.

**Comment by gmbecker** [comment]
@Melkiades please have a look at the new title/footer/footnote vignette I have just added, and at the modifications I made to the subsetting vignette to hopefully make pathing a little more clear.

**Comment by Melkiades** [comment]
Great job!! I am reading them
