### ISSUE TITLE
Formatting with fixed number of digits

### ISSUE THREAD

**Issue by vpilliano** [Roche/rtables#416]
When I use analyze and specify a format with decimals, e.g. xx.xx, I wish the number of digits to be fixed

Example:

```r
library(rtables)

l <- basic_table() %>%
    split_cols_by("Species") %>%
    analyze(head(names(iris), -1), afun = function(x) {
        list(
            "mean / sd" = rcell(c(mean(x), sd(x)), format = "xx.xx (xx.xx)"),
            "range" = rcell(diff(range(x)), format = "xx.xx")
        )
    })
l
build_table(l, iris)
```
This gives:

![image](https://user-images.githubusercontent.com/91895444/195319530-0f4d71f2-ee05-4ed4-8f04-3236de1a41a9.png)

Even though we specified xx.xx for range, we get only one decimal (because the second is zero). 
This choice is questionable in the first place because the number of decimals may indicate the measures' precision.
Furthermore, it becomes questionable from a look perspective when the number of decimals varies, like for virginica's Sepal.Length, which is the only value with no decimals (3).

**Comment by Melkiades** [comment]
On my local machine, it works as you intended. Which version are you running?

**Comment by vpilliano** [comment]
Thanks @Melkiades , 
I am using rtables 0.5.1 
Could it be some R setting that differ between my environment and yours?

**Comment by gmbecker** [comment]
Indeed, this has been fixed in the development version (for quite some time now) and the fix will be present in the next CRAN release, which should be sometime this month, I believe.
