### ISSUE TITLE
export_as_pdf doesn't work with default front size 18. Works with smaller front size 8 

### ISSUE THREAD

**Issue by crazycatandy** [Roche/rtables#421]
```
Starting: t_ae 
Error in .local(x, ...) : length(widths) == ncol(mat$strings) is not TRUE
```
Data is shared via Email
Code can be found: https://code.roche.com/citril_demo/citril_demo/-/blob/main/Workflow_example.Rmd

**Comment by crazycatandy** [comment]
Also, should I ignore warnings: Warning in new_line_warning(allfoots) :
  Detected manual newlines when automatic title/footer word-wrapping is on.This is unsupported and will result in undefined behavior. Please either utilize automatic word-wrapping with newline characters inserted, or turn off automatic wrapping and wordwrap all contents manually by inserting newlines.
W

**Comment by gmbecker** [comment]
@crazycatandy The warning is correct (and means what it says). There are three ways to get title/footer materials to fit where you want them to go now.

1.  You can insert `\n` into the strings, which is supported (though i'd say its soft deprected)
  - if you do this you'll want to do `tf_wrap = FALSE` to avoid the warning, but as I Said its no longer the 'right' way to do it 
2. You can give single strings and have word wrapping on (by default it is for pdfs)
3. You can give vectors of already split entries which will each get their own line(/paragraph before wrapping if that is also on).

Does that make sense?

**Comment by crazycatandy** [comment]
> title/footer materials

Hi [lil128](https://github.roche.com/lil128), we need to do more testing in the next PI to see how to walk around warnings if possible.

**Comment by crazycatandy** [comment]
> ```
> Starting: t_ae 
> Error in .local(x, ...) : length(widths) == ncol(mat$strings) is not TRUE
> ```
> 
> Data is shared via Email Code can be found: https://code.roche.com/citril_demo/citril_demo/-/blob/main/Workflow_example.Rmd

Hi Gabe, what about this error when using default front size 12?

**Comment by gmbecker** [comment]
Unfortunately, AFAIK I cannot access the data your script uses that raised that error.

What are the values of `widths` and of `dim(mat$strings)` when that error occurs?

**Comment by crazycatandy** [comment]
> Unfortunately, AFAIK I cannot access the data your script uses that raised that error.
> 
> What are the values of `widths` and of `dim(mat$strings)` when that error occurs?

Hi Gabe, I have sent you an email with the attached test data we used as an rds file. If you can't find it anymore I can send again.

**Comment by gmbecker** [comment]
@crazycatandy the issue was having newlines in the provenance footer, which was running afoul of something when word wrapping for titles/footers is enabled (which it is by default in export_as_pdf). That is now fixed, but again, moving forward, we don't want to be using embedded `\n` anymore, approach (2) or (3) in my comment above are what we want to be doing.

Also, `pg_width` and `pg_height` are in inches, so those are definitely not the correct values for those. If you want to specify in characters, you should set `lpp` and `cpp` directly rather than relying on page size.
