### ISSUE TITLE
Make the output table justified

### ISSUE THREAD

**Issue by vpilliano** [Roche/rtables#430]
Can the rtables ouput be justified?
By default columns are centered, but is it possible to have them justified too?
I have not found any info on this

Thanks!

**Comment by gmbecker** [comment]
Hi @vpilliano

Yes, both `rcell` and `in_rows` accept aligntment information (the `align` and `.aligns` arguments, respectively).

Currently the allowed values are `"left"`, `"center"` (default), and `"right"`

From our tests:
```

    lyt <- basic_table() %>%
        analyze("AGE", function(x) {
            in_rows(left = rcell("l", align = "left"),
                    right = rcell("r", align = "right"),
                    center = rcell("c", align = "center"))
        })

    ## set the hsep so it works the same in all locales since thats not what
    ## we are testing
    aligntab <- build_table(lyt, DM, hsep = "=")
```

which gives
```
> aligntab
         all obs
================
left     l      
right          r
center      c   
```
