### ISSUE TITLE
tt_to_flextable: Remove top lines when there is no title

### ISSUE THREAD

**Issue by dmenne** [Roche/rtables#441]
When there is no title/subtitle, there are 2 redundant lines at the top of the table when using `tt_to_flextable`. It looks like these are hard-wired in the function. `flextable/borders_remove` can remove all borders, but I have not found a function for single lines.

My suggestion: Allow for explicit title = NULL, same for subtitle to suppress the line.

**Comment by dmenne** [comment]
Quick workaround in tt_to_flextable

     if (length(all_titles(tt)) > 0 && all_titles(tt)[1] != "") {
     .....

**Comment by dmenne** [comment]
This could also be a bug or inconsistency in TableTree: Note that main_title is "", while the others are chr(0), so length(all_titles()) will never be 0.

```
Formal class 'TableTree' [package "rtables"] with 16 slots
  ..@ content          :Formal class 'ElementaryTable' [package "rtables"] with 15 slots
  ..@ page_title_prefix: chr NA
  ..@ children         :List of 2
  ..@ rowspans         :'data.frame':	0 obs. of  0 variables
  ..@ labelrow         :Formal class 'LabelRow' [package "rtables"] with 10 slots
  ..@ page_titles      : chr(0) 
  ..@ horizontal_sep   : chr "—"
  ..@ col_info         :Formal class 'InstantiatedColumnInfo' [package "rtables"] with 8 slots
  ..@ format           : NULL
  ..@ indent_modifier  : int 0
  ..@ level            : int 1
  ..@ name             : chr "SEX"
  ..@ main_title       : chr ""
  ..@ subtitles        : chr(0) 
  ..@ main_footer      : chr(0) 
  ..@ provenance_footer: chr(0) 

```

**Comment by gmbecker** [comment]
@dmenne thanks for the report I will look into this.

**Comment by gmbecker** [comment]
@dmenne please give this a look, I believe the issue is fixed but if it persists or comes back please reopen the issue

**Comment by dmenne** [comment]
Ok. Thanks
