### ISSUE TITLE
rtables version

### ISSUE THREAD

**Issue by crazycatandy** [Roche/rtables#444]
Which version of rtables 
1)supports using “\n” (Not producing errors - 
![image](https://user-images.githubusercontent.com/39836652/200895594-d574bf0c-eea1-4c55-a062-523fcd976b57.png)
):

2)can do the right pagination when using \n in text 
as well as 3) can be installed on enableR R3.6.3?

**Comment by waddella** [comment]
@crazycatandy:

(1.  & 2.)`rtables` as from `v0.4.1.002` supports `\n` and paginates correctly (https://github.com/Roche/rtables/issues/309)

(3.) upgrading `rtables` & `formatters` on a production server is something you need to discuss with the `enableR` business owner and the NEST release owner.

**Comment by crazycatandy** [comment]
hi @waddella and @gmbecker 
Just wondering how am I able to install this version of rtables?
