### ISSUE TITLE
Team familiarize themselves with modern documentation around design and philosophy of rtables

### ISSUE THREAD

**Issue by gmbecker** [Roche/rtables#445]
Go through RinPharma slides: https://docs.google.com/presentation/d/1t0098eh1b8_FaFfRoD7jhP1nxhLmjrJeD5X5MkmKC48

- [x] @ayogasekaram 
- [x] @Melkiades 
- [x] @edelarua

**Comment by edelarua** [comment]
I have finished reading the presentation.

A few spelling/grammar/formatting notes to clean up the slides:
- slide 33 - change "tern" font to Courier New (to match previous slide)
- slide 39 - change %>% to |>
- slide 69 - typo: "rables"
- slide 97 - grammar: remove "is"
- slide 105 - typo: "Absolut"
- slide 107 - typo: ".We"

**Comment by ayogasekaram** [comment]
A few comments.
- slide 67 - change %>% to |>
- slide 69 - split and analyze should be a different font (matching function font)
- slide 117 - add colon "if:"

**Comment by Melkiades** [comment]
Nice presentation!! I think it is quite useful and there are a few things we can work on (like a vignette for custom split function and split context)
