### ISSUE TITLE
Pagination with wrapped titles/footers not working

### ISSUE THREAD

**Issue by edelarua** [Roche/rtables#447]
Wrapping titles/footnotes are not working properly for `paginate_table`.

Example:

```r
library(rtables)

lyt <- basic_table() %>%
    split_cols_by("SEX") %>%
    analyze("RACE")

tt <- build_table(lyt, DM)

main_title(tt) <- "this is a long long table title that should be wrapped to a new line"
subtitles(tt) <- c("sub", "-------", "titles")
main_footer(tt) <- "this is an extra long table main footer and should also be wrapped"
prov_footer(tt) <- "prov footer"

paginate_table(tt, cpp = 60, tf_wrap = TRUE)
```
Note: Main footer is 66 characters wide, main title is 68 characters wide

Output:
```
[[1]]
this is a long long table title that should be wrapped to a new line
sub
-------
titles

—————————————————————————————————————————————————————————
                                             F     M    U
—————————————————————————————————————————————————————————
ASIAN                                       121   110   0
BLACK OR AFRICAN AMERICAN                   43    36    0
WHITE                                       23    23    0
AMERICAN INDIAN OR ALASKA NATIVE             0     0    0
MULTIPLE                                     0     0    0
NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER    0     0    0
OTHER                                        0     0    0
UNKNOWN                                      0     0    0
—————————————————————————————————————————————————————————

this is an extra long table main footer and should also be wrapped

prov footer

[[2]]
this is a long long table title that should be wrapped to a new line
sub
-------
titles

————————————————————————————————————————————————————————————
                                            UNDIFFERENTIATED
————————————————————————————————————————————————————————————
ASIAN                                              0        
BLACK OR AFRICAN AMERICAN                          0        
WHITE                                              0        
AMERICAN INDIAN OR ALASKA NATIVE                   0        
MULTIPLE                                           0        
NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER          0        
OTHER                                              0        
UNKNOWN                                            0        
————————————————————————————————————————————————————————————

this is an extra long table main footer and should also be wrapped

prov footer
```

**Comment by gmbecker** [comment]
Hi Emily,

Pagination does not control rendering, it only identifies pagination breaks. Furthermore, table objects do not carry around their word-wrapping information, that occurs only at rendering time, so this is unintuitive, but expected behavior.


See `export_as_txt`, which does both:

```
> cat(export_as_txt(tt, cpp = 60, tf_wrap = TRUE, page_break = "\n---xxxx---\n\n", paginate = TRUE))
this is a long long table title that should be wrapped to a
new line
sub
-------
titles

—————————————————————————————————————————————————————————
                                             F     M    U
—————————————————————————————————————————————————————————
ASIAN                                       121   110   0
BLACK OR AFRICAN AMERICAN                   43    36    0
WHITE                                       23    23    0
AMERICAN INDIAN OR ALASKA NATIVE             0     0    0
MULTIPLE                                     0     0    0
NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER    0     0    0
OTHER                                        0     0    0
UNKNOWN                                      0     0    0
—————————————————————————————————————————————————————————

this is an extra long table main footer and should also be
wrapped

prov footer

---xxxx---

this is a long long table title that should be wrapped to a
new line
sub
-------
titles

————————————————————————————————————————————————————————————
                                            UNDIFFERENTIATED
————————————————————————————————————————————————————————————
ASIAN                                              0        
BLACK OR AFRICAN AMERICAN                          0        
WHITE                                              0        
AMERICAN INDIAN OR ALASKA NATIVE                   0        
MULTIPLE                                           0        
NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER          0        
OTHER                                              0        
UNKNOWN                                            0        
————————————————————————————————————————————————————————————

this is an extra long table main footer and should also be
wrapped

prov footer
> 
```


This should be more prominently documented than it is, please file a new issue to figure out where that should go and then do so.

**Comment by edelarua** [comment]
> Hi Emily,
> 
> Pagination does not control rendering, it only identifies pagination breaks. Furthermore, table objects do not carry around their word-wrapping information, that occurs only at rendering time, so this is unintuitive, but expected behavior.
> 
> See `export_as_txt`, which does both:
> 
> ```
> > cat(export_as_txt(tt, cpp = 60, tf_wrap = TRUE, page_break = "\n---xxxx---\n\n", paginate = TRUE))
> this is a long long table title that should be wrapped to a
> new line
> sub
> -------
> titles
> 
> —————————————————————————————————————————————————————————
>                                              F     M    U
> —————————————————————————————————————————————————————————
> ASIAN                                       121   110   0
> BLACK OR AFRICAN AMERICAN                   43    36    0
> WHITE                                       23    23    0
> AMERICAN INDIAN OR ALASKA NATIVE             0     0    0
> MULTIPLE                                     0     0    0
> NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER    0     0    0
> OTHER                                        0     0    0
> UNKNOWN                                      0     0    0
> —————————————————————————————————————————————————————————
> 
> this is an extra long table main footer and should also be
> wrapped
> 
> prov footer
> 
> ---xxxx---
> 
> this is a long long table title that should be wrapped to a
> new line
> sub
> -------
> titles
> 
> ————————————————————————————————————————————————————————————
>                                             UNDIFFERENTIATED
> ————————————————————————————————————————————————————————————
> ASIAN                                              0        
> BLACK OR AFRICAN AMERICAN                          0        
> WHITE                                              0        
> AMERICAN INDIAN OR ALASKA NATIVE                   0        
> MULTIPLE                                           0        
> NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER          0        
> OTHER                                              0        
> UNKNOWN                                            0        
> ————————————————————————————————————————————————————————————
> 
> this is an extra long table main footer and should also be
> wrapped
> 
> prov footer
> > 
> ```
> 
> This should be more prominently documented than it is, please file a new issue to figure out where that should go and then do so.

Great, will do. Thanks Gabe!

**Comment by Melkiades** [comment]
I have a consideration regarding this: would it be possible to have the wrapping also in the print calls? I think it makes sense that people would use the console first to look at the wrapping and set the relevant values before using the pagination and export machinery.

**Comment by gmbecker** [comment]
@Melkiades Assuming you mean automatic printing (which are similar but not the same as explicit print calls) this would be a significant change, because the `TableTree` object would need to carry around width information, which doesn't necessarily make a ton  of sense when you can export the same object to both HTML that doesn't need to fit on a page and txt/PDF/RTF which does.

One possible way around this would be to make the wordwrapping "hard" instead of "soft" (which is what it is now). Hard word wrapping would be actually transforming the values of things by inserting hard newlines, whereas soft wordwrapping is "when you go to print it, wrap the full text to the desired width").

I don't think we can go that route though, because while it would work for title/footer information, it won't work for cell values.

**Comment by Melkiades** [comment]
I agree the second option is not a viable one. Having it hard coded means that getters would output it with the newline which can be a real problem downstream.  My comment regarded mainly the possibility to keep the width as an optional parameter in the `TableTree` object along with another flag like `as_printout` which would always give a preview of the final table with the wrapping. But I understand it is a lot to add and there is no guarantee that all of this would be useful ^^
