### ISSUE TITLE
Correct `colcount` usage throughout all documentation and vignettes

### ISSUE THREAD

**Issue by Melkiades** [Roche/rtables#451]
This is no longer the idiomatically correct way to do this (`basic_table(show_colcount = TRUE)` is). Please correct this usage throughout all documentation and vignettes.

_Originally posted by @gmbecker in https://github.com/Roche/rtables/pull/438#discussion_r1019542717_

**Comment by gmbecker** [comment]
Thanks for following up on this @Melkiades but I made this part of #446 so we don't need a separate issue for it.
