### ISSUE TITLE
How `lpp` counts the lines per page with cell wrapping?

### ISSUE THREAD

**Issue by Melkiades** [Roche/rtables#455]
Here I could be very wrong as I do not know exactly how `lpp` (lines per page) counts the number of lines in a table. Nonetheless, I produce the following by using `lpp = 15` and I do not count a global 15 number of lines. Code to generate it lies below:
![Screenshot 2022-11-15 184022](https://user-images.githubusercontent.com/11279768/201989266-08681ea6-eb63-499c-a901-9e7c61cdf1af.png)
```r
library(rtables)
library(dplyr)
clw <- c(5, 7, 6, 6) + 3

trimmed_data <- ex_adsl %>% 
    filter(SEX %in% c("M", "F")) %>% 
    filter(RACE %in% levels(RACE)[1:2]) 

levels(trimmed_data$ARM)[1] <- "Incredibly long column name to be wrapped"
levels(trimmed_data$ARM)[2] <- "This_should_be_somewhere_split"

tbl <- basic_table() %>%
    split_cols_by("ARM") %>%
    split_rows_by("RACE", split_fun = drop_split_levels) %>%
    analyze(c("AGE", "EOSDY"), 
            na_str = "A very long content to_be_wrapped_and_splitted",
            inclNAs = TRUE) %>%
    build_table(trimmed_data)

export_as_pdf(tbl, file = "to_del.pdf", paginate = T, colwidths = clw, lpp = 15)
```
Coming from #450. I was also wondering here how to test that also the column labels are rightfully wrapped (`nrow(tbl)` works only for content right?). Should I test that separately?

**Comment by gmbecker** [comment]
Yes, this pagination is wrong.

**Comment by gmbecker** [comment]
Specifically, its because of the issue where the separator is in the wrong place (or rather, they are both because of the same underlying bug, which is that the `nlines` method for `InstantiatedColumnInfo` is not determining the correct number of lines for the table header.

**Comment by gmbecker** [comment]
This has since been fixed, closing as completed.
