### ISSUE TITLE
Why subsetting loses title and subtitles when there are columns while not the footers? Is it expected?

### ISSUE THREAD

**Issue by Melkiades** [Roche/rtables#456]
This a rare case, I think but I encountered it while testing specific parts of the table for which I used a lot of subsetting. To reproduce it run the following:
```r
library(rtables)
tbl <- basic_table(title = "a", subtitles = "b", main_footer = "c", prov_footer = "d") %>%
    split_rows_by("SEX") %>% 
    split_cols_by("ARM") %>%  # if this is omitted title and subtitles work
    analyze("AGE") %>%
    build_table(ex_adsl)

cat(toString(matrix_form(tbl[2,1], TRUE)))
```
When fixed, this needs a change in tests like for #457

**Comment by gmbecker** [comment]
There are actually 2 bugs here:

First is that the footer materials are not lost (all annotation materials should be lost on `[` subsetting)

The second is what you were asking about. You're right that the behavior should *not* be different in the case where there is no column splitting, thats a bug (as well)

**Comment by gmbecker** [comment]
@Melkiades do you want to take a pass at one or both of these bugs?

**Comment by Melkiades** [comment]
So the standard is to lose all the titles and footnotes on subsetting? I checked and also referential footnotes are retained:
```r
fnotes_at_path(tbl, rowpath = c("SEX", "F", "AGE", "Mean")) <- "sadsadsafagfrgtregr"
cat(toString(matrix_form(tbl[2,1], TRUE)))
```
![Screenshot 2022-11-15 202127](https://user-images.githubusercontent.com/11279768/202007122-d03403b2-714e-4166-9c06-06837370dd9e.png)

Should we drop also this after subsetting?

**Comment by gmbecker** [comment]
Referential footnotes that are associated with retained elements  should be the only things that are retained, according to the current design.

An argument could be made for the provenance footer, although a strong argument against can as well. The rest should not, as they often describe things about the table that are no longer accurate of just the subset.

Note they can be retained by doing

```
tbl[i, j, keep_titles = TRUE]
```
Which is intended to control all non-referential header and footer materials (but apparently isn't working).

The same should happen for topleft materials, dropped by default, kept by doing

```
tbl[i,j, keep_topleft = TRUE]
```

Regarding referential footnotes (which as I said should be retained if the elements they are attached to are), by default they are reindexed (ie the counting to get the number associated with them is redone) and that can be turned off (as it is in the pagination machinery automatically), via

```
tbl[i,j, reindex_refs = FALSE]
```
