### ISSUE TITLE
wrapping of row names should have identical indentions

### ISSUE THREAD

**Issue by clarkliming** [Roche/rtables#469]
currently the wrapped row labels looks very strange

![image](https://user-images.githubusercontent.com/36079400/203227795-48c597e4-40b9-4612-b3a6-fb74c06fd977.png)

we should make the wrapped text have the same indention

**Comment by Melkiades** [comment]
This is possibly a bug. Can I ask you for a reproducible example?

**Comment by gmbecker** [comment]
This will actually be in formatters, but the behavior will show up here automatically once fixed there. See the `toString` `MatrixPrintForm` method.
