### ISSUE TITLE
Use add_overall_level only if more than 1 column

### ISSUE THREAD

**Issue by PaulinCharliquart** [Roche/rtables#481]
hi,

I would like to add the "All" column only if I have more than 1 column in rtables.

I was able to do that with this code:

```r
library(rtables)
library(dplyr)

adsl <- iris

adsl_one_obs <- adsl %>%
  filter(Species == "setosa") %>%
  mutate(Species := as.character(Species))

test <- function(df, var) {
  obs <- unique(df[[var]])
  if (length(obs)>1) {
    add_overall_level("All", first = FALSE)
  }
}

rtables::basic_table() %>%
  rtables::split_cols_by("Species", split_fun = test(adsl_one_obs, "Species")) %>%
  rtables::add_colcounts() %>%
  rtables::analyze(vars = "Sepal.Length") %>%
  rtables::build_table(adsl_one_obs)


rtables::basic_table() %>%
  rtables::split_cols_by("Species", split_fun = test(adsl, "Species")) %>%
  rtables::add_colcounts() %>%
  rtables::analyze(vars = "Sepal.Length") %>%
  rtables::build_table(adsl)

```

I tried to customize the split function by following this [doc](https://roche.github.io/rtables/reference/custom_split_funs.html) but I do not know how to use it with `add_overall_level`.

Do you have any suggestions?

Thanks

**Comment by Melkiades** [comment]
I am unsure what is the question. It seems you are successfully using `add_overall_level` for your purpose. Alternatively, I got the same result by doing this:
```r
rtables::basic_table() %>%
  rtables::split_cols_by("Species") %>%
  rtables::add_colcounts() %>%
  rtables::add_overall_col("All") %>%
  rtables::analyze(vars = "Sepal.Length") %>%
  rtables::build_table(adsl)
```
Maybe, if you print the desired format I can help you better ^^

**Comment by Melkiades** [comment]
PS: use https://roche.github.io/rtables/main/reference/custom_split_funs.html instead of the link you posted. This is the current documentation website

**Comment by gmbecker** [comment]
Hi @PaulinCharliquart, apologies for the delayed response.

You can do this via a custom split function. There are a few different flavors, the one that doesn't require anything that isn't currently exported (but that I willb e exporting in response to this issue) is the following. Here we define a function constructor which accepts the variable name we want to check, and then return a custom split function that has the behavior you want using functions provided by `rtables` for both cases:

```
picky_splitter <- function(var) {
    function(df, spl, vals, labels, trim) {
        orig_vals <- vals
        if (is.null(vals)) {
            vec <- df[[var]]
            vals <- if(is.factor(vec)) levels(vec) else unique(vec)
        }
        if (length(vals) == 1)
            do_base_split(spl = spl, df = df, vals = vals, labels = labels, trim = trim)
        else
            add_overall_level("Overall", label = "All Obs", first = FALSE)(df = df, spl = spl,
                vals = orig_vals, trim = trim)
    }
}


d1 <- subset(ex_adsl, ARM == "A: Drug X")
d1$ARM <- factor(d1$ARM)

lyt1 <- basic_table() %>%
    split_cols_by("ARM", split_fun = picky_splitter("ARM")) %>%
    analyze("AGE")
```

```
> build_table(lyt1, d1)
       A: Drug X
————————————————
Mean     33.77  
> build_table(lyt1, ex_adsl)
       A: Drug X   B: Placebo   C: Combination   All Obs
————————————————————————————————————————————————————————
Mean     33.77       35.43          35.43         34.88 
```

Notice we use `add_overall_level` which is itself a function constructor, and then immediately call the constructed function in the more-than-one-columns case.

I will be adding a discussion of this usecase to the advanced usage vignette I'm compiling.
