### ISSUE TITLE
Problem with sorting and mixed nesting

### ISSUE THREAD

**Issue by Melkiades** [Roche/rtables#487]
I am probably doing something wrong in my sorting but I cannot manage to get a result as it keeps giving me back "has no content table". This is coming from https://github.com/insightsengineering/tern/issues/748 where the original code used a similar way to sort the values but it was using `summarize_row_groups` instead of `analyze`. Here, I made a simpler example:
```r
library(rtables)
lyt <- basic_table(show_colcounts = TRUE) %>%
  split_cols_by("ARM") %>%
  add_overall_col("Overall") %>%
  analyze(vars = "AGE", mean, inclNAs = FALSE) %>%
  split_rows_by("RACE",
                child_labels = "visible",
                nested = FALSE,
                split_fun = drop_split_levels) %>%
  analyze("AGE", afun = mean,
          nested = TRUE, inclNAs = FALSE,
          show_labels = "hidden")
(tbl <- build_table(lyt, DM))
```
Different error outputs:
```r
> row_paths_summary(tbl)
rowname                      node_class    path                                            
———————————————————————————————————————————————————————————————————————————————————————————
mean                         DataRow       root, AGE, mean                                 
ASIAN                        LabelRow      root, RACE, ASIAN                               
  mean                       DataRow       root, RACE, ASIAN, AGE, mean                    
BLACK OR AFRICAN AMERICAN    LabelRow      root, RACE, BLACK OR AFRICAN AMERICAN           
  mean                       DataRow       root, RACE, BLACK OR AFRICAN AMERICAN, AGE, mean
WHITE                        LabelRow      root, RACE, WHITE                               
  mean                       DataRow       root, RACE, WHITE, AGE, mean                    
> sort_at_path(tbl, path = c("root"), scorefun = cont_n_onecol(4))
Error: Encountered at least 2 error(s) when applying score function.
First error: cont_n_allcols score function used at subtable [AGE] that has no content table.
	occurred at path: AGE
> sort_at_path(tbl, path = c("RACE"), scorefun = cont_n_onecol(4))
Error: Encountered at least 3 error(s) when applying score function.
First error: cont_n_allcols score function used at subtable [ASIAN] that has no content table.
	occurred at path: RACE -> ASIAN
> sort_at_path(tbl, path = c("RACE", "*"), scorefun = cont_n_onecol(4))
Error: Encountered at least 1 error(s) when applying score function.
First error: cont_n_allcols score function used at subtable [AGE] that has no content table.
occurred at path: RACE -> * (ASIAN) -> AGE
> sort_at_path(tbl, path = c("RACE", "*", "AGE"), scorefun = cont_n_onecol(4))
Error: Encountered at least 1 error(s) when applying score function.
First error: cont_n_allcols score function used at subtable [mean] that has no content table.
occurred at path: RACE -> * (ASIAN) -> AGE -> mean
> sort_at_path(tbl, path = c("RACE", "*", "AGE", "mean"), scorefun = cont_n_onecol(4))
Error in order(scores, na.last = (na.pos != "first"), decreasing = decreasing) :
argument 1 is not a vector
```

So is the score function the one I need? I tried to make my own but I am a bit unsure on input/output there. Is there a collection of sorting functions to be used?

PS: the original sorting was using only `sort_at_path(tbl, path = c("RACE"), scorefun = cont_n_onecol(4))` to do it, but it used `summarize_row_groups` instead of `analyze`

**Comment by clarkliming** [comment]
Hi @Melkiades maybe for now, we can use "analyze" under root, and use "summarize" under each split. Hopefully under each split there won't be too many replicated information.... 

if we are switching  all to analyze, by default, the score fun of cont_n_xx things is based on the content of the row split, we need another function to extract the patient number, i.e. score_fun = analyze_n_onecol(column, row) where row can be the index of the analyze index

**Comment by shajoezhu** [comment]
@Melkiades @clarkliming I think this is a discussion in tern for how we utilize rtables,

> we can use "analyze" under root, and use "summarize" under each split.
agree

we might need two set of functions in some cases, both analyze and summerize

**Comment by clarkliming** [comment]
> we might need two set of functions in some cases, both analyze and summerize

Thanks @shajoezhu this is exactly what I meant in the very beginning

**Comment by gmbecker** [comment]
`cont_n_onecol` is a score function that uses the values of a facet's content (ie row group summary) row to sort sibling facets. This does not make sense for facets that don't have content, and so it does not work.

Score functions are specific and should not be blindly used across different application. Every time you sort you need to think about exactly what you want the sorting behavior to be. I mentioned this in another issue somewhere, though I don't know where it was right now.

**Comment by gmbecker** [comment]
The other issue was #465 

Specifically my comment at https://github.com/Roche/rtables/issues/465#issuecomment-1324384590

Closing issue.
