### ISSUE TITLE
How to install rtables v0.4.1.0002 on R 3.6.3? -URGENT for study GB43311

### ISSUE THREAD

**Issue by crazycatandy** [Roche/rtables#492]
Just wondering how am I able to install  v0.4.1.0002 as a user?

**Comment by crazycatandy** [comment]
I tried to install the rtables-0.4.1.tar.gz but seems like the changes made on v0.4.1.0002 doesn't reflect there?

**Comment by crazycatandy** [comment]
ref: #444

**Comment by crazycatandy** [comment]
seems like rtables-2022_01_28.tar.gz worked. Thanks

**Comment by gmbecker** [comment]
@crazycatandy `0.4.1.0002` is not a bundled release, its an automatic version increment after an individual pull request. This is not a version of `rtables` which has been tested and is ready for production use. Why is it being given to a study team?
