### ISSUE TITLE
Improve the error message of "bline %in% vals" [example still work in progress]

### ISSUE THREAD

**Issue by shajoezhu** [Roche/rtables#499]
# Reporting an Issue with rtables

Please briefly describe your problem and, when relevant, the output you expect.
Please also provide the output of `utils::sessionInfo()` or
`devtools::session_info()` at the end of your post.

If at all possible, please include a [minimal, reproducible
example](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example).
The `rtables` team will be much more likely to resolve your issue if they are
able to reproduce it themselves locally.

Please delete this preamble after you have read it.

---

your brief description of the problem

```r
library(rtables)

# your reproducible example here

```

**Comment by gmbecker** [comment]
@shajoezhu any progress on a reproducible example?

**Comment by Melkiades** [comment]
I have never encountered this issue so far. We can close this for now and reopen it when it is ready

**Comment by shajoezhu** [comment]
We have encounteded this twice when running with real study work. it was fixed with data preprocessing.

but this error was thrown, and was very not informative, and misleading for debugging. i am trying to find a case to reproduce the bug. 

but the error message itself, "bline %in% vals", what does it mean? @gmbecker

**Comment by Melkiades** [comment]
If it helps this can come only from the following piece of code:
```r
setMethod("set_def_child_ord", "VarLevWBaselineSplit",
          function(lyt, df) {
    bline <- spl_ref_group(lyt)
    if(!is.null(spl_child_order(lyt)) &&
       match(bline, spl_child_order(lyt), nomatch = -1) == 1L)
        return(lyt)

    if(!is.null(split_fun(lyt))) {
        ## expensive but sadly necessary, I think
        pinfo <- do_split(lyt, df, spl_context = context_df_row())
        vals <- sort(unlist(value_names(pinfo$values)))
    } else {
        vec <- df[[spl_payload(lyt)]]
        vals <- if(is.factor(vec))
                levels(vec)
            else
                unique(vec)

        if(is.factor(vals)) {
            ## this sorts the levels
            vals <- levels(relevel(droplevels(vals), bline))
        }
    }

    stopifnot(bline %in% vals) # HERE
    pos <- match(bline, vals)
    ## same order except ref_group always first
    vals <- c(bline, vals[-pos])
    spl_child_order(lyt) <- vals
    lyt
})

```

**Comment by gmbecker** [comment]
This means that the reference group value specified via `split_cols_by(var, ref_group = <>)` when splitting was not present in the levels of `<var>` in the data

**Comment by gmbecker** [comment]
Closing this issue should be as simple as changing that `stopifnot` to `if(...) stop(...)` where `stop` is constructing a more informative error message.

**Comment by shajoezhu** [comment]
> This means that the reference group value specified via split_cols_by(var, ref_group = <>) when splitting was not present in the levels of <var> in the data

I would say this is a much more informative error message "This means that the reference group value specified via split_cols_by(var, ref_group = <>) when splitting was not present in the levels of <var> in the data"

**Comment by gmbecker** [comment]
I was (somewhat naively it seems) assuming it would never happen as
illustrated by the fact that its a raw stopifnot. This shoukd be something
anyone who hS been working with me can change a nd make a small pr for

**Comment by Melkiades** [comment]
@BFalquet fyi

**Comment by gmbecker** [comment]
@shajoezhu can you point an sme team member at this issue?
