### ISSUE TITLE
Is it possible to specify different statistics for different visits in an rtable

### ISSUE THREAD

**Issue by juliadedic1** [Roche/rtables#501]
Hi team! 

Is there a way to specify which statistics we want to display depending on the visit? The reason I ask is we have an MMRM table that looks like this: 

![image](https://user-images.githubusercontent.com/99106549/213239975-376400e3-ce3c-40d5-b96f-70ed18e9f612.png)

Notice that Week 4 doesn't have the difference in adjusted means, 95% CI for differences in adjusted means or p-value where all other visits in the table do. The reason for this is due to NA's appearing in Week 4.

Is something like this possible in the current rtables framework? Is this something we could think about adding in the future?

Thanks!

Best,

Julia

**Comment by Melkiades** [comment]
I think you can. Intuitively I would do first a split for `VISIT` variable, then I would use the variable `.spl_context` in the analyze function to select different statistical methods. Can I ask you to write a small example in `rtables` on which we can try this idea?

**Comment by juliadedic1** [comment]
Hi @Melkiades thanks for your reponse. Here is a small example using the example dataset in the `tern.mmrm` package.

```
mmrm_results <- fit_mmrm(
  vars = list(
    response = "FEV1",
    covariates = c("RACE", "SEX"),
    id = "USUBJID",
    arm = "ARMCD",
    visit = "AVISIT"
  ),
  data = mmrm_test_data,
  cor_struct = "unstructured",
  weights_emmeans = "equal"
  )

df <- tidy(mmrm_results)

split_fun <- drop_split_levels

result <- basic_table() %>%
  split_cols_by("ARMCD", ref_group = mmrm_results$ref_level) %>%
  add_colcounts() %>%
  split_rows_by("AVISIT", split_fun = split_fun, label_pos = "topleft", split_label = "Visit") %>%
  summarize_lsmeans(show_relative = "increase", .stats = c("n", "adj_mean_se", "adj_mean_ci", "diff_mean_se", "diff_mean_ci"),
                    .labels = c(n = "N", adj_mean_se = "Adjusted Mean (SE)", adj_mean_ci = "95% CI for Adjusted Mean", diff_mean_ci = "95% CI for Difference in Adjusted Means"),
                    .formats = c(adj_mean_se = sprintf_format("%.1f (%.2f)"), adj_mean_ci = sprintf_format("(%.1f, %.1f)"),
                                 diff_mean_se = sprintf_format("%.1f (%.2f)"), diff_mean_ci = sprintf_format("(%.1f, %.1f)"))
  ) %>%
  append_topleft("  Statistics") %>%
  build_table(df)

```

Suppose in this example, we want for visit "VIS1" only to display N, Adjusted Mean (SE), and 95% CI for Adjusted Mean and keep all other visits as is. 

Thanks for your help!!

**Comment by juliadedic1** [comment]
Thanks a lot @gmbecker! I will try it out :)
