### ISSUE TITLE
Discussion for the not too close future: documenting objects and their functions

### ISSUE THREAD

**Issue by Melkiades** [Roche/rtables#533]
This is very low-priority but I was recently looking at the documentation of https://github.com/insightsengineering/teal.data/blob/main/R/TealData.R and how it is structured, both in terms of code and docs. I think it is easily readable and accessible. @gmbecker I am aware that R6 objects pass by reference and you do not like them understandably (and changing everything from s4 to r6 is not practical), but I was wondering if it is possible to structure the docs/code similarly (sometimes I lose myself a bit ^^). I was wondering also why @gogonzo and core-team made teal.data with R6 also

**Comment by shajoezhu** [comment]
please consider this from user perspective. r6 is way too complex for most of users, and very hard to debug. i would like to avoid the use of r6

**Comment by gmbecker** [comment]
We won't be using `R6` for `rtables`, it isn't even on the table so long as I'm the one who is making that decision @shajoezhu, so don't worry about that.

@Melkiades In terms of organization of code, I personally think organizing methods by generic i better than organizing code by class (also, keep in my S4 has multiple dispatch, so its not clear how attempting to organize methods by class would even work).

Giving the teal developers the benefit of the doubt, without having been involved in the decision making at all, it could be that they are using R6 becuse tthey are an interactive application where latency is very important, which is _nearly_ the only valid reason to use something with reference mechanics in R software.

**Comment by Melkiades** [comment]
Thanks @gmbecker for the explanation! :)

**Comment by gogonzo** [comment]
@Melkiades at this moment I don't remember reasoning behind. We used to consider R6 having good encapsulation but at some point we noticed the drawbacks especially when the class grew. There is a plan to simplify teal.data just to list of data or simple S4 class. We already started some decoupling but the main refactor will start after filter-panel is done.
