### ISSUE TITLE
`extra_args` does not work

### ISSUE THREAD

**Issue by waddella** [Roche/rtables#75]
The following code gives an error

```
basic_table() %>%
  analyze("Sepal.Length", afun = function(x, a) {
     in_rows(mean_a = rcell(mean(x) + a , format = "xx"))
     
  }, extra_args = list( a = 1)) %>%
  build_table(iris)
```

with the error

```
Error in is(x, "CellValue") : argument "a" is missing, with no default
```

**Comment by danielinteractive** [comment]
I would highly recommend to add a corresponding unit test so that we don't get this bug again. Thanks.

**Comment by gmbecker** [comment]
extra_args is used in a vignette but in a different way, but yes I will add
a regression test once this is fixed.

**Comment by gmbecker** [comment]
Fixed with regression test.
