### ISSUE TITLE
`add_colcounts()` fails when applied without column split

### ISSUE THREAD

**Issue by danielinteractive** [Roche/rtables#78]
The example below gives an error: `Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘disp_ccounts<-’ for signature ‘"NULL"’`

```
basic_table() %>% 
  add_colcounts() %>%
  analyze("AGE") %>%
  build_table(DM)
```

Expected result:
```
        all obs  
       (N=356)
--------------
Mean    34.22 
```

**Comment by gmbecker** [comment]
fixed with regression test in 219ed52
