### ISSUE TITLE
Feature Request: Allow rowspan, too

### ISSUE THREAD

**Issue by billdenney** [Roche/rtables#9]
In the examples and vignette, `colspan` is an attribute of a cell-- could rowspan also be an attribute?  That would allow simplification of grouping on the row level.

Row spanning doesn't easily work with every output type (e.g. markdown), and for that, I could imagine a feature which would allow a function to define the behavior taking an input of the contents.  Some defaults off the top of my head could be `rowspan_blank(x)`, `rowspan_duplicate(x)`, `rowspan_text(x, value="(continued)")`.

**Comment by billdenney** [comment]
Hi @waddella,

Thanks for the response.  I see the times when indentation can overlap the need for rowspanning, but it is not a complete replacement for my use cases.

As a potential interface, perhaps something like the following could be possible in the future:

``` r
rtable(
  header = c("Group", "X", "Y"),
  rrow("Group 1",
    rtable(
      rrow("A", 1, 2),
      rrow("B", 3, 4)
    )
  ),
  rrow("Group 2",
    rtable(
      rrow("C", 5, 6),
      rrow("D", 7, 8)
    )
  )
)
```

I can imagine that this would be a very significant change in the back-end, but it becomes very helpful when the text in the "Group" column wraps to many lines of text so that the values in "X" and "Y" columns are not excessively spaced.

FYI, it is important enough for me that I helped with the creation of a LaTeX package to support multi-page row-spanning with more human-readable output: https://github.com/billdenney/topiclongtable

**Comment by waddella** [comment]
Hi @billdenney,

Thank you very much for providing the reference to your topiclongtable project. Currently this would be a significant back-end change but I am planning a re-design of the object data structure anyway. I will leave this issue open and revisit it when I get around to work on the next re-design.

Best,
Adrian

**Comment by billdenney** [comment]
Thanks for considering it!

**Comment by waddella** [comment]
@billdenney, have you had a look at the current new release of `rtables`. It's a full refactor of `rtables` from 2018 when you wrote this issue. We don't have rowspans as it does not fit into the way we

- tabulate tables
- chose the data structure of tables (i.e. rows are completely independent stored)

We are not currently working on that.

I will close the issue. If you are using the new rtables package and you still feel like you need rowspans, then please reopen the issue.

Best,
Adrian
